// Copyright 2026 The gophonic authors
// SPDX-License-Identifier: BSD-2-Clause

// Package chat defines model-independent text generation. A Generator holds
// a language model; each Session is one conversation, whose context the
// model keeps evaluated between replies, so a new message costs only its own
// tokens. A Tool is a function the model may call, and Answer is the loop
// that replies, runs the calls, and replies again. Like package speech it
// imports no model code: any backend can implement it, and gophonic models
// provide it as a lane.
package chat

import (
	"context"
	"errors"
	"io"
)

// Role is the author of a message.
type Role uint8

const (
	System Role = iota
	User
	Assistant
	// ToolResult is the result of a Call, added after the reply that made
	// it.
	ToolResult
)

// ToolSpec describes a function the model may call instead of, or as well
// as, answering in words. Parameters is the JSON Schema of its arguments
// object; empty takes none.
type ToolSpec struct {
	Name        string
	Description string
	Parameters  string
}

// Call is a call the model made in a reply: a declared tool's name and its
// arguments as a JSON object. Arguments belongs to the session and is
// valid until the next Reply.
type Call struct {
	Name      string
	Arguments []byte
}

// Options controls one reply. The zero value decodes greedily until the
// model ends its message.
type Options struct {
	// MaxTokens bounds the reply; zero means no bound but the context.
	MaxTokens int
	// Temperature scales the logits before sampling; zero picks the most
	// likely token every step.
	Temperature float32
	// TopK keeps only the TopK most likely tokens; zero keeps them all.
	TopK int
	// TopP keeps the smallest set of most likely tokens whose probability
	// reaches TopP; zero or one keeps them all.
	TopP float32
	// Presence lowers the logit of every token the reply already holds by
	// this much, against repetition; Qwen3.6's non-thinking mode is tuned
	// for 1.5. Zero penalizes nothing.
	Presence float32
	// Seed seeds sampling; replies with equal seeds and inputs are equal.
	Seed uint64
}

// Generator is a loaded language model that holds conversations.
type Generator interface {
	// NewSession starts a conversation, with system as its system prompt
	// when not empty, that may call the tools described.
	NewSession(system string, tools ...ToolSpec) (Session, error)
	Close() error
}

// Session is one conversation. It is not safe for concurrent use; sessions
// of one Generator may be used concurrently and share its model.
type Session interface {
	// Add appends a complete message to the conversation without replying.
	// It does not retain text.
	Add(role Role, text string) error
	// Reply generates the assistant's next message, writing its text to w
	// as it is decoded, in pieces that end on UTF-8 boundaries; w must not
	// retain a piece. The message ends when the model ends it, after
	// Options.MaxTokens tokens, when w returns an error (returned by
	// Reply), or when ctx is done. The text generated by then stays in the
	// conversation as a complete message. Warm replies allocate nothing.
	// Tool calls are not text: they go to Calls, not to w.
	Reply(ctx context.Context, opts Options, w io.Writer) error
	// Calls returns the tool calls of the last reply, in order, valid
	// until the next Reply. Their results join the conversation as Tool
	// messages; a Reply after them answers knowing them.
	Calls() []Call
	// Finished returns the probability that a message of role ends after
	// text rather than going on, perhaps after closing punctuation: the
	// model's sense, from the words and the conversation, of whether a
	// speaker is done. What it evaluates is kept, as by Prefill, so adding
	// the message next costs nothing more, and judging the same message
	// again costs nothing.
	Finished(ctx context.Context, role Role, text string) (float32, error)
	// Prefill evaluates the conversation as it stands, so that the next
	// Reply starts at once. A message added speculatively, prefilled, and
	// dropped by Restore leaves what it shares with the message that
	// replaces it evaluated, as when a transcript grows while it is spoken.
	Prefill(ctx context.Context) error
	// Truncate shortens the last reply to its first n bytes (rounded down
	// to a token boundary), as when a listener interrupts spoken output
	// and only part of it was heard.
	Truncate(n int) error
	// Checkpoint marks the conversation as it is; Restore returns to a
	// mark, forgetting everything added since, as when a reply prepared
	// speculatively is dropped. What stays evaluated is reused.
	Checkpoint() int
	Restore(mark int) error
	Close() error
}

// A Tool is a function the model may call: its spec tells the model what
// it does, and Call does it, given the model's arguments as a JSON
// object. Tools are slow paths, a lookup or a clock, and may allocate.
// Func makes one of a typed Go function.
type Tool interface {
	Spec() ToolSpec
	Call(ctx context.Context, arguments []byte) (result string, err error)
}

// Specs returns the tools' specs, as NewSession takes them.
func Specs(tools []Tool) []ToolSpec {
	specs := make([]ToolSpec, len(tools))
	for i, t := range tools {
		specs[i] = t.Spec()
	}
	return specs
}

// Answer replies to the conversation as it stands, writing the words to w,
// runs the calls the reply made, adds their results, and replies again
// knowing them, up to rounds replies: the loop every agent runs. A call to
// a tool the session was not offered, or one that fails, gets an error
// result the model can read. The last reply's calls, if any, are left in
// s.Calls.
func Answer(ctx context.Context, s Session, tools []Tool, opts Options, w io.Writer, rounds int) error {
	for round := 0; ; round++ {
		if err := s.Reply(ctx, opts, w); err != nil {
			return err
		}
		calls := s.Calls()
		if len(calls) == 0 || round+1 >= rounds {
			return nil
		}
		for _, call := range calls {
			if err := s.Add(ToolResult, Run(ctx, tools, call)); err != nil {
				return err
			}
		}
	}
}

// Run performs call with the tool of its name and returns the result, or
// an error message the model can read.
func Run(ctx context.Context, tools []Tool, call Call) string {
	for _, t := range tools {
		if t.Spec().Name != call.Name {
			continue
		}
		result, err := t.Call(ctx, call.Arguments)
		if err != nil {
			return "error: " + err.Error()
		}
		return result
	}
	return "error: there is no tool " + call.Name
}

// ErrClosed is returned by calls on a closed Generator or Session.
var ErrClosed = errors.New("chat: closed")
