// Copyright 2026 The gophonic authors
// SPDX-License-Identifier: BSD-2-Clause

// Package chat defines model-independent text generation. A Generator holds
// a language model; each Session is one conversation, whose context the
// model keeps evaluated between replies, so a new message costs only its own
// tokens. Like package speech it imports no model code: any backend can
// implement it, and gophonic models provide it as a lane.
package chat

import (
	"context"
	"errors"
)

// Role is the author of a message.
type Role uint8

const (
	System Role = iota
	User
	Assistant
	// Tool is the result of a Call, added after the reply that made it.
	Tool
)

// ToolSpec is a function the model may call instead of, or as well as,
// answering in words: to act on the world, or on the conversation itself
// ("be quiet until I say hi"). Parameters is the JSON Schema of its
// arguments object; empty takes none.
type ToolSpec struct {
	Name        string
	Description string
	Parameters  string
}

// Call is a call the model made in a reply: a declared tool's name and its
// arguments as a JSON object.
type Call struct {
	Name      string
	Arguments []byte
}

// Options controls one reply. The zero value decodes greedily until the
// model ends its message.
type Options struct {
	// MaxTokens bounds the reply; zero means no bound but the context.
	MaxTokens int
	// Temperature scales the logits before sampling; zero picks the most
	// likely token every step.
	Temperature float32
	// TopK keeps only the TopK most likely tokens; zero keeps them all.
	TopK int
	// TopP keeps the smallest set of most likely tokens whose probability
	// reaches TopP; zero or one keeps them all.
	TopP float32
	// Seed seeds sampling; replies with equal seeds and inputs are equal.
	Seed uint64
}

// Generator is a loaded language model that holds conversations.
type Generator interface {
	// NewSession starts a conversation, with system as its system prompt
	// when not empty, that may call tools.
	NewSession(system string, tools ...ToolSpec) (Session, error)
	Close() error
}

// Session is one conversation. It is not safe for concurrent use; sessions
// of one Generator may be used concurrently and share its model.
type Session interface {
	// Add appends a complete message to the conversation without replying.
	Add(role Role, text string) error
	// Reply generates the assistant's next message, passing its text to
	// sink as it is decoded, in pieces that end on UTF-8 boundaries; sink
	// must not retain a piece. The message ends when the model ends it,
	// after Options.MaxTokens tokens, when sink returns an error (returned
	// by Reply), or when ctx is done. The text generated by then stays in
	// the conversation as a complete message. Warm replies allocate
	// nothing. Tool calls are not text: they go to Calls, not to sink.
	Reply(ctx context.Context, opts Options, sink func(piece []byte) error) error
	// Calls returns the tool calls of the last reply, in order, valid
	// until the next Reply. Their results join the conversation as Tool
	// messages; a Reply after them answers knowing them.
	Calls() []Call
	// Finished returns the probability that a message of role ends after
	// text rather than going on, perhaps after closing punctuation: the
	// model's sense, from the words and the conversation, of whether a
	// speaker is done: whether the words end there, and whether the
	// message ends after the closing punctuation it has, if any, which
	// speech recognizers write at every pause. What it evaluates is kept,
	// as by Prefill, so adding the message next costs nothing more, and
	// judging the same message again costs nothing.
	Finished(ctx context.Context, role Role, text string) (float32, error)
	// Prefill evaluates the conversation as it stands, so that the next
	// Reply starts at once. A message added speculatively, prefilled, and
	// dropped by Restore leaves what it shares with the message that
	// replaces it evaluated, as when a transcript grows while it is spoken.
	Prefill(ctx context.Context) error
	// Truncate shortens the last reply to its first n bytes (rounded down
	// to a token boundary), as when a listener interrupts spoken output
	// and only part of it was heard.
	Truncate(n int) error
	// Checkpoint marks the conversation as it is; Restore returns to a
	// mark, forgetting everything added since, as when a reply prepared
	// speculatively is dropped. What stays evaluated is reused.
	Checkpoint() int
	Restore(mark int) error
	Close() error
}

// ErrClosed is returned by calls on a closed Generator or Session.
var ErrClosed = errors.New("chat: closed")
