// Copyright 2026 The gophonic authors
// SPDX-License-Identifier: BSD-2-Clause

// Package chat defines model-independent text generation. A Generator holds
// a language model; each Session is one conversation, whose context the
// model keeps evaluated between replies, so a new message costs only its own
// tokens. Like package speech it imports no model code: any backend can
// implement it, and gophonic models provide it as a lane.
package chat

import (
	"context"
	"errors"
)

// Role is the author of a message.
type Role uint8

const (
	System Role = iota
	User
	Assistant
)

// Options controls one reply. The zero value decodes greedily until the
// model ends its message.
type Options struct {
	// MaxTokens bounds the reply; zero means no bound but the context.
	MaxTokens int
	// Temperature scales the logits before sampling; zero picks the most
	// likely token every step.
	Temperature float32
	// TopK keeps only the TopK most likely tokens; zero keeps them all.
	TopK int
	// TopP keeps the smallest set of most likely tokens whose probability
	// reaches TopP; zero or one keeps them all.
	TopP float32
	// Seed seeds sampling; replies with equal seeds and inputs are equal.
	Seed uint64
}

// Generator is a loaded language model that holds conversations.
type Generator interface {
	// NewSession starts a conversation, with system as its system prompt
	// when not empty.
	NewSession(system string) (Session, error)
	Close() error
}

// Session is one conversation. It is not safe for concurrent use; sessions
// of one Generator may be used concurrently and share its model.
type Session interface {
	// Add appends a complete message to the conversation without replying.
	Add(role Role, text string) error
	// Reply generates the assistant's next message, passing its text to
	// sink as it is decoded, in pieces that end on UTF-8 boundaries; sink
	// must not retain a piece. The message ends when the model ends it,
	// after Options.MaxTokens tokens, when sink returns an error (returned
	// by Reply), or when ctx is done. The text generated by then stays in
	// the conversation as a complete message. Warm replies allocate
	// nothing.
	Reply(ctx context.Context, opts Options, sink func(piece []byte) error) error
	// Truncate shortens the last reply to its first n bytes (rounded down
	// to a token boundary), as when a listener interrupts spoken output
	// and only part of it was heard.
	Truncate(n int) error
	// Checkpoint marks the conversation as it is; Restore returns to a
	// mark, forgetting everything added since, as when a reply prepared
	// speculatively is dropped. What stays evaluated is reused.
	Checkpoint() int
	Restore(mark int) error
	Close() error
}

// ErrClosed is returned by calls on a closed Generator or Session.
var ErrClosed = errors.New("chat: closed")
