#!/usr/bin/env python3
"""Regenerate ../sme_arm64.s from the SME sources in this directory.

Go's assembler has no SME mnemonics, so clang assembles each kernel and the
encodings are embedded as WORD directives. Run from this directory:

    python3 build.py
"""
import os, subprocess, sys

here = os.path.dirname(os.path.abspath(__file__))
os.chdir(here)
subprocess.check_call([sys.executable, "gemv.py", "gemv"])

def words(src):
    return subprocess.check_output([sys.executable, "gen.py", src]).decode()

def text(name, args, frame, loads, src, ret):
    out = [f"// func {name}{args}", f"TEXT ·{name}(SB), NOSPLIT, $0-{frame}"]
    for off, reg, arg in loads:
        out.append(f"\tMOVD\t{arg}+{off}(FP), R{reg}")
    out.append(words(src).rstrip("\n"))
    out.append(f"\tMOVD\tR0, {ret}(FP)")
    out.append("\tRET\n")
    return "\n".join(out)

gemv_args = [(0, 0, "x"), (8, 1, "k"), (16, 2, "w"), (24, 3, "n"), (32, 4, "y"), (40, 5, "kp")]
parts = [
    "// Code generated by smesrc/build.py; DO NOT EDIT.\n\n//go:build arm64\n\n#include \"textflag.h\"\n",
    text("smeMulBlock", "(a *float32, lda, rows, k int, b *float32, n int, c *float32, ldc int, scratch *float32) (retries int)",
         80, [(0, 0, "a"), (8, 1, "lda"), (16, 2, "rows"), (24, 3, "k"), (32, 4, "b"),
              (40, 5, "n"), (48, 6, "c"), (56, 7, "ldc"), (64, 8, "scratch")], "block.S", "retries+72"),
    text("smeVectorF32", "(x *float32, k int, w *float32, n int, y *float32, kp int) (retries int)",
         56, gemv_args, "gemv_f32.S", "retries+48"),
    text("smeVectorF16", "(x *float32, k int, w *uint16, n int, y *float32, kp int) (retries int)",
         56, gemv_args, "gemv_f16.S", "retries+48"),
    "// func smeVectorBytes() int\nTEXT ·smeVectorBytes(SB), NOSPLIT, $0-8\n\tWORD\t$0x04bf5820\t// rdsvl x0, #1\n\tMOVD\tR0, ret+0(FP)\n\tRET\n",
]
open("../sme_arm64.s", "w").write("\n".join(parts))
