// Code generated by smesrc/build.py; DO NOT EDIT.

//go:build arm64

#include "textflag.h"

// func smeMulBlock(a *float32, lda, rows, k int, b *float32, n int, c *float32, ldc int, scratch *float32) (retries int)
TEXT ·smeMulBlock(SB), NOSPLIT, $0-80
	MOVD	a+0(FP), R0
	MOVD	lda+8(FP), R1
	MOVD	rows+16(FP), R2
	MOVD	k+24(FP), R3
	MOVD	b+32(FP), R4
	MOVD	n+40(FP), R5
	MOVD	c+48(FP), R6
	MOVD	ldc+56(FP), R7
	MOVD	scratch+64(FP), R8
	WORD	$0xd503477f	// smstart
	WORD	$0x2598e3e0	// ptrue p0.s
	WORD	$0x25a07810	// ptrue pn8.s
	WORD	$0xd2800011	// mov x17, #0x0 ; =0
	WORD	$0xd2800009	// mov x9, #0x0 ; =0
	WORD	$0xd2800210	// mov x16, #0x10 ; =16
	WORD	$0xc0080033	// zero {za0.s,za1.s}
	WORD	$0x25a31521	// whilelt p1.s, x9, x3
	WORD	$0x8b09080a	// add x10, x0, x9, lsl #2
	WORD	$0x5280000c	// mov w12, #0x0 ; =0
	WORD	$0xeb02019f	// cmp x12, x2
	WORD	$0x5400016a	// b.ge 0x58
	WORD	$0xf100419f	// cmp x12, #0x10
	WORD	$0x5400006a	// b.ge 0x40
	WORD	$0xe09f0540	// ld1w {za0h.s[w12, 0]}, p1/z, [x10]
	WORD	$0x14000003	// b 0x48
	WORD	$0x5100418d	// sub w13, w12, #0x10
	WORD	$0xe09f2544	// ld1w {za1h.s[w13, 0]}, p1/z, [x10]
	WORD	$0x8b01014a	// add x10, x10, x1
	WORD	$0x1100058c	// add w12, w12, #0x1
	WORD	$0xf100819f	// cmp x12, #0x20
	WORD	$0x54fffeab	// b.lt 0x28
	WORD	$0x8b091d0b	// add x11, x8, x9, lsl #7
	WORD	$0x5280000c	// mov w12, #0x0 ; =0
	WORD	$0xe0bf8160	// st1w {za0v.s[w12, 0]}, p0, [x11]
	WORD	$0xe0b08164	// st1w {za1v.s[w12, 0]}, p0, [x11, x16, lsl #2]
	WORD	$0x9102016b	// add x11, x11, #0x80
	WORD	$0x1100058c	// add w12, w12, #0x1
	WORD	$0x7100419f	// cmp w12, #0x10
	WORD	$0x54ffff6b	// b.lt 0x60
	WORD	$0x91004129	// add x9, x9, #0x10
	WORD	$0xeb03013f	// cmp x9, x3
	WORD	$0x54fffccb	// b.lt 0x18
	WORD	$0xd37ae46f	// lsl x15, x3, #6
	WORD	$0xd280000e	// mov x14, #0x0 ; =0
	WORD	$0xaa0403eb	// mov x11, x4
	WORD	$0x910041cd	// add x13, x14, #0x10
	WORD	$0xeb0501bf	// cmp x13, x5
	WORD	$0x9a84a08a	// csel x10, x4, x4, ge
	WORD	$0x8b0f008c	// add x12, x4, x15
	WORD	$0x9a8ab18a	// csel x10, x12, x10, lt
	WORD	$0xc00800ff	// zero {za}
	WORD	$0x25b9ce1f	// fmov z31.s, #1.00000000
	WORD	$0xaa0803e9	// mov x9, x8
	WORD	$0xaa0b03ed	// mov x13, x11
	WORD	$0xaa0a03ec	// mov x12, x10
	WORD	$0xaa0303f0	// mov x16, x3
	WORD	$0xf100121f	// cmp x16, #0x4
	WORD	$0x540005eb	// b.lt 0x17c
	WORD	$0xa040c120	// ld1w { z0.s - z3.s }, pn8/z, [x9]
	WORD	$0xa04041a4	// ld1w { z4.s, z5.s }, pn8/z, [x13]
	WORD	$0xa0404186	// ld1w { z6.s, z7.s }, pn8/z, [x12]
	WORD	$0x91040129	// add x9, x9, #0x100
	WORD	$0x910201ad	// add x13, x13, #0x80
	WORD	$0x9102018c	// add x12, x12, #0x80
	WORD	$0xa040c128	// ld1w { z8.s - z11.s }, pn8/z, [x9]
	WORD	$0xa04041ac	// ld1w { z12.s, z13.s }, pn8/z, [x13]
	WORD	$0xa040418e	// ld1w { z14.s, z15.s }, pn8/z, [x12]
	WORD	$0x91040129	// add x9, x9, #0x100
	WORD	$0x910201ad	// add x13, x13, #0x80
	WORD	$0x9102018c	// add x12, x12, #0x80
	WORD	$0x80840000	// fmopa za0.s, p0/m, p0/m, z0.s, z4.s
	WORD	$0x80860001	// fmopa za1.s, p0/m, p0/m, z0.s, z6.s
	WORD	$0x80840022	// fmopa za2.s, p0/m, p0/m, z1.s, z4.s
	WORD	$0x80860023	// fmopa za3.s, p0/m, p0/m, z1.s, z6.s
	WORD	$0x80850040	// fmopa za0.s, p0/m, p0/m, z2.s, z5.s
	WORD	$0x80870041	// fmopa za1.s, p0/m, p0/m, z2.s, z7.s
	WORD	$0x80850062	// fmopa za2.s, p0/m, p0/m, z3.s, z5.s
	WORD	$0x80870063	// fmopa za3.s, p0/m, p0/m, z3.s, z7.s
	WORD	$0xd1001210	// sub x16, x16, #0x4
	WORD	$0xf100121f	// cmp x16, #0x4
	WORD	$0x5400020b	// b.lt 0x15c
	WORD	$0xa040c120	// ld1w { z0.s - z3.s }, pn8/z, [x9]
	WORD	$0xa04041a4	// ld1w { z4.s, z5.s }, pn8/z, [x13]
	WORD	$0xa0404186	// ld1w { z6.s, z7.s }, pn8/z, [x12]
	WORD	$0x91040129	// add x9, x9, #0x100
	WORD	$0x910201ad	// add x13, x13, #0x80
	WORD	$0x9102018c	// add x12, x12, #0x80
	WORD	$0x808c0100	// fmopa za0.s, p0/m, p0/m, z8.s, z12.s
	WORD	$0x808e0101	// fmopa za1.s, p0/m, p0/m, z8.s, z14.s
	WORD	$0x808c0122	// fmopa za2.s, p0/m, p0/m, z9.s, z12.s
	WORD	$0x808e0123	// fmopa za3.s, p0/m, p0/m, z9.s, z14.s
	WORD	$0x808d0140	// fmopa za0.s, p0/m, p0/m, z10.s, z13.s
	WORD	$0x808f0141	// fmopa za1.s, p0/m, p0/m, z10.s, z15.s
	WORD	$0x808d0162	// fmopa za2.s, p0/m, p0/m, z11.s, z13.s
	WORD	$0x808f0163	// fmopa za3.s, p0/m, p0/m, z11.s, z15.s
	WORD	$0x17ffffe1	// b 0xdc
	WORD	$0x808c0100	// fmopa za0.s, p0/m, p0/m, z8.s, z12.s
	WORD	$0x808e0101	// fmopa za1.s, p0/m, p0/m, z8.s, z14.s
	WORD	$0x808c0122	// fmopa za2.s, p0/m, p0/m, z9.s, z12.s
	WORD	$0x808e0123	// fmopa za3.s, p0/m, p0/m, z9.s, z14.s
	WORD	$0x808d0140	// fmopa za0.s, p0/m, p0/m, z10.s, z13.s
	WORD	$0x808f0141	// fmopa za1.s, p0/m, p0/m, z10.s, z15.s
	WORD	$0x808d0162	// fmopa za2.s, p0/m, p0/m, z11.s, z13.s
	WORD	$0x808f0163	// fmopa za3.s, p0/m, p0/m, z11.s, z15.s
	WORD	$0xb40001d0	// cbz x16, 0x1b4
	WORD	$0xa540a120	// ld1w { z0.s }, p0/z, [x9]
	WORD	$0xa541a121	// ld1w { z1.s }, p0/z, [x9, #0x1, mul vl]
	WORD	$0xa540a1a2	// ld1w { z2.s }, p0/z, [x13]
	WORD	$0xa540a183	// ld1w { z3.s }, p0/z, [x12]
	WORD	$0x80820000	// fmopa za0.s, p0/m, p0/m, z0.s, z2.s
	WORD	$0x80830001	// fmopa za1.s, p0/m, p0/m, z0.s, z3.s
	WORD	$0x80820022	// fmopa za2.s, p0/m, p0/m, z1.s, z2.s
	WORD	$0x80830023	// fmopa za3.s, p0/m, p0/m, z1.s, z3.s
	WORD	$0x91020129	// add x9, x9, #0x80
	WORD	$0x910101ad	// add x13, x13, #0x40
	WORD	$0x9101018c	// add x12, x12, #0x40
	WORD	$0xd1000610	// sub x16, x16, #0x1
	WORD	$0x17fffff3	// b 0x17c
	WORD	$0x2598e3e3	// ptrue p3.s
	WORD	$0x65922fe4	// fcmeq p4.s, p3/z, z31.s, #0.0
	WORD	$0x2550cc80	// ptest p3, p4.b
	WORD	$0x540000e1	// b.ne 0x1dc
	WORD	$0x25a08c09	// cntp x9, p3, p0.s
	WORD	$0xf100413f	// cmp x9, #0x10
	WORD	$0x54000081	// b.ne 0x1dc
	WORD	$0x25a08709	// cntp x9, pn8.s, vlx4
	WORD	$0xf101013f	// cmp x9, #0x40
	WORD	$0x540000a0	// b.eq 0x1ec
	WORD	$0x91000631	// add x17, x17, #0x1
	WORD	$0x2598e3e0	// ptrue p0.s
	WORD	$0x25a07810	// ptrue pn8.s
	WORD	$0x17ffffaf	// b 0xa4
	WORD	$0xcb0e00a9	// sub x9, x5, x14
	WORD	$0xd2800210	// mov x16, #0x10 ; =16
	WORD	$0x25a917e1	// whilelt p1.s, xzr, x9
	WORD	$0x25a91602	// whilelt p2.s, x16, x9
	WORD	$0x8b0e08cd	// add x13, x6, x14, lsl #2
	WORD	$0x5280000c	// mov w12, #0x0 ; =0
	WORD	$0xf100405f	// cmp x2, #0x10
	WORD	$0x9a90b049	// csel x9, x2, x16, lt
	WORD	$0xeb09019f	// cmp x12, x9
	WORD	$0x540000ca	// b.ge 0x228
	WORD	$0xe0bf05a0	// st1w {za0h.s[w12, 0]}, p1, [x13]
	WORD	$0xe0b009a4	// st1w {za1h.s[w12, 0]}, p2, [x13, x16, lsl #2]
	WORD	$0x8b0701ad	// add x13, x13, x7
	WORD	$0x1100058c	// add w12, w12, #0x1
	WORD	$0x17fffffa	// b 0x20c
	WORD	$0xd1004049	// sub x9, x2, #0x10
	WORD	$0x5280000c	// mov w12, #0x0 ; =0
	WORD	$0xeb09019f	// cmp x12, x9
	WORD	$0x540000ca	// b.ge 0x24c
	WORD	$0xe0bf05a8	// st1w {za2h.s[w12, 0]}, p1, [x13]
	WORD	$0xe0b009ac	// st1w {za3h.s[w12, 0]}, p2, [x13, x16, lsl #2]
	WORD	$0x8b0701ad	// add x13, x13, x7
	WORD	$0x1100058c	// add w12, w12, #0x1
	WORD	$0x17fffffa	// b 0x230
	WORD	$0x910081ce	// add x14, x14, #0x20
	WORD	$0x8b0f0484	// add x4, x4, x15, lsl #1
	WORD	$0xeb0501df	// cmp x14, x5
	WORD	$0x54fff1ab	// b.lt 0x8c
	WORD	$0xd503467f	// smstop
	WORD	$0xaa1103e0	// mov x0, x17
	MOVD	R0, retries+72(FP)
	RET

// func smeVectorF32(x *float32, k int, w *float32, n int, y *float32, kp int) (retries int)
TEXT ·smeVectorF32(SB), NOSPLIT, $0-56
	MOVD	x+0(FP), R0
	MOVD	k+8(FP), R1
	MOVD	w+16(FP), R2
	MOVD	n+24(FP), R3
	MOVD	y+32(FP), R4
	MOVD	kp+40(FP), R5
	WORD	$0xd503477f	// smstart
	WORD	$0x2598e3e0	// ptrue p0.s
	WORD	$0x25a07810	// ptrue pn8.s
	WORD	$0x25607811	// ptrue pn9.h
	WORD	$0xd2800011	// mov x17, #0x0 ; =0
	WORD	$0x9100fc6d	// add x13, x3, #0x3f
	WORD	$0xd346fdad	// lsr x13, x13, #6
	WORD	$0xd2800006	// mov x6, #0x0 ; =0
	WORD	$0xaa0203f0	// mov x16, x2
	WORD	$0xd2800107	// mov x7, #0x8 ; =8
	WORD	$0xf10021bf	// cmp x13, #0x8
	WORD	$0x9a87b1a7	// csel x7, x13, x7, lt
	WORD	$0xc00800ff	// zero {za}
	WORD	$0x25b9ce1f	// fmov z31.s, #1.00000000
	WORD	$0xd2800009	// mov x9, #0x0 ; =0
	WORD	$0xaa0003ea	// mov x10, x0
	WORD	$0xaa1003eb	// mov x11, x16
	WORD	$0x52800008	// mov w8, #0x0 ; =0
	WORD	$0xf10020ff	// cmp x7, #0x8
	WORD	$0x54000d01	// b.ne 0x1ec
	WORD	$0x25a11521	// whilelt p1.s, x9, x1
	WORD	$0xa5002548	// ld1rqw { z8.s }, p1/z, [x10]
	WORD	$0xa040c164	// ld1w { z4.s - z7.s }, pn8/z, [x11]
	WORD	$0x9104016b	// add x11, x11, #0x100
	WORD	$0xc1588080	// fmla za.s[w8, 0, vgx4], { z4.s - z7.s }, z8.s[0]
	WORD	$0xa040c16c	// ld1w { z12.s - z15.s }, pn8/z, [x11]
	WORD	$0x9104016b	// add x11, x11, #0x100
	WORD	$0xc1588181	// fmla za.s[w8, 1, vgx4], { z12.s - z15.s }, z8.s[0]
	WORD	$0xa040c164	// ld1w { z4.s - z7.s }, pn8/z, [x11]
	WORD	$0x9104016b	// add x11, x11, #0x100
	WORD	$0xc1588082	// fmla za.s[w8, 2, vgx4], { z4.s - z7.s }, z8.s[0]
	WORD	$0xa040c16c	// ld1w { z12.s - z15.s }, pn8/z, [x11]
	WORD	$0x9104016b	// add x11, x11, #0x100
	WORD	$0xc1588183	// fmla za.s[w8, 3, vgx4], { z12.s - z15.s }, z8.s[0]
	WORD	$0xa040c164	// ld1w { z4.s - z7.s }, pn8/z, [x11]
	WORD	$0x9104016b	// add x11, x11, #0x100
	WORD	$0xc1588084	// fmla za.s[w8, 4, vgx4], { z4.s - z7.s }, z8.s[0]
	WORD	$0xa040c16c	// ld1w { z12.s - z15.s }, pn8/z, [x11]
	WORD	$0x9104016b	// add x11, x11, #0x100
	WORD	$0xc1588185	// fmla za.s[w8, 5, vgx4], { z12.s - z15.s }, z8.s[0]
	WORD	$0xa040c164	// ld1w { z4.s - z7.s }, pn8/z, [x11]
	WORD	$0x9104016b	// add x11, x11, #0x100
	WORD	$0xc1588086	// fmla za.s[w8, 6, vgx4], { z4.s - z7.s }, z8.s[0]
	WORD	$0xa040c16c	// ld1w { z12.s - z15.s }, pn8/z, [x11]
	WORD	$0x9104016b	// add x11, x11, #0x100
	WORD	$0xc1588187	// fmla za.s[w8, 7, vgx4], { z12.s - z15.s }, z8.s[0]
	WORD	$0xa040c164	// ld1w { z4.s - z7.s }, pn8/z, [x11]
	WORD	$0x9104016b	// add x11, x11, #0x100
	WORD	$0xc1588480	// fmla za.s[w8, 0, vgx4], { z4.s - z7.s }, z8.s[1]
	WORD	$0xa040c16c	// ld1w { z12.s - z15.s }, pn8/z, [x11]
	WORD	$0x9104016b	// add x11, x11, #0x100
	WORD	$0xc1588581	// fmla za.s[w8, 1, vgx4], { z12.s - z15.s }, z8.s[1]
	WORD	$0xa040c164	// ld1w { z4.s - z7.s }, pn8/z, [x11]
	WORD	$0x9104016b	// add x11, x11, #0x100
	WORD	$0xc1588482	// fmla za.s[w8, 2, vgx4], { z4.s - z7.s }, z8.s[1]
	WORD	$0xa040c16c	// ld1w { z12.s - z15.s }, pn8/z, [x11]
	WORD	$0x9104016b	// add x11, x11, #0x100
	WORD	$0xc1588583	// fmla za.s[w8, 3, vgx4], { z12.s - z15.s }, z8.s[1]
	WORD	$0xa040c164	// ld1w { z4.s - z7.s }, pn8/z, [x11]
	WORD	$0x9104016b	// add x11, x11, #0x100
	WORD	$0xc1588484	// fmla za.s[w8, 4, vgx4], { z4.s - z7.s }, z8.s[1]
	WORD	$0xa040c16c	// ld1w { z12.s - z15.s }, pn8/z, [x11]
	WORD	$0x9104016b	// add x11, x11, #0x100
	WORD	$0xc1588585	// fmla za.s[w8, 5, vgx4], { z12.s - z15.s }, z8.s[1]
	WORD	$0xa040c164	// ld1w { z4.s - z7.s }, pn8/z, [x11]
	WORD	$0x9104016b	// add x11, x11, #0x100
	WORD	$0xc1588486	// fmla za.s[w8, 6, vgx4], { z4.s - z7.s }, z8.s[1]
	WORD	$0xa040c16c	// ld1w { z12.s - z15.s }, pn8/z, [x11]
	WORD	$0x9104016b	// add x11, x11, #0x100
	WORD	$0xc1588587	// fmla za.s[w8, 7, vgx4], { z12.s - z15.s }, z8.s[1]
	WORD	$0xa040c164	// ld1w { z4.s - z7.s }, pn8/z, [x11]
	WORD	$0x9104016b	// add x11, x11, #0x100
	WORD	$0xc1588880	// fmla za.s[w8, 0, vgx4], { z4.s - z7.s }, z8.s[2]
	WORD	$0xa040c16c	// ld1w { z12.s - z15.s }, pn8/z, [x11]
	WORD	$0x9104016b	// add x11, x11, #0x100
	WORD	$0xc1588981	// fmla za.s[w8, 1, vgx4], { z12.s - z15.s }, z8.s[2]
	WORD	$0xa040c164	// ld1w { z4.s - z7.s }, pn8/z, [x11]
	WORD	$0x9104016b	// add x11, x11, #0x100
	WORD	$0xc1588882	// fmla za.s[w8, 2, vgx4], { z4.s - z7.s }, z8.s[2]
	WORD	$0xa040c16c	// ld1w { z12.s - z15.s }, pn8/z, [x11]
	WORD	$0x9104016b	// add x11, x11, #0x100
	WORD	$0xc1588983	// fmla za.s[w8, 3, vgx4], { z12.s - z15.s }, z8.s[2]
	WORD	$0xa040c164	// ld1w { z4.s - z7.s }, pn8/z, [x11]
	WORD	$0x9104016b	// add x11, x11, #0x100
	WORD	$0xc1588884	// fmla za.s[w8, 4, vgx4], { z4.s - z7.s }, z8.s[2]
	WORD	$0xa040c16c	// ld1w { z12.s - z15.s }, pn8/z, [x11]
	WORD	$0x9104016b	// add x11, x11, #0x100
	WORD	$0xc1588985	// fmla za.s[w8, 5, vgx4], { z12.s - z15.s }, z8.s[2]
	WORD	$0xa040c164	// ld1w { z4.s - z7.s }, pn8/z, [x11]
	WORD	$0x9104016b	// add x11, x11, #0x100
	WORD	$0xc1588886	// fmla za.s[w8, 6, vgx4], { z4.s - z7.s }, z8.s[2]
	WORD	$0xa040c16c	// ld1w { z12.s - z15.s }, pn8/z, [x11]
	WORD	$0x9104016b	// add x11, x11, #0x100
	WORD	$0xc1588987	// fmla za.s[w8, 7, vgx4], { z12.s - z15.s }, z8.s[2]
	WORD	$0xa040c164	// ld1w { z4.s - z7.s }, pn8/z, [x11]
	WORD	$0x9104016b	// add x11, x11, #0x100
	WORD	$0xc1588c80	// fmla za.s[w8, 0, vgx4], { z4.s - z7.s }, z8.s[3]
	WORD	$0xa040c16c	// ld1w { z12.s - z15.s }, pn8/z, [x11]
	WORD	$0x9104016b	// add x11, x11, #0x100
	WORD	$0xc1588d81	// fmla za.s[w8, 1, vgx4], { z12.s - z15.s }, z8.s[3]
	WORD	$0xa040c164	// ld1w { z4.s - z7.s }, pn8/z, [x11]
	WORD	$0x9104016b	// add x11, x11, #0x100
	WORD	$0xc1588c82	// fmla za.s[w8, 2, vgx4], { z4.s - z7.s }, z8.s[3]
	WORD	$0xa040c16c	// ld1w { z12.s - z15.s }, pn8/z, [x11]
	WORD	$0x9104016b	// add x11, x11, #0x100
	WORD	$0xc1588d83	// fmla za.s[w8, 3, vgx4], { z12.s - z15.s }, z8.s[3]
	WORD	$0xa040c164	// ld1w { z4.s - z7.s }, pn8/z, [x11]
	WORD	$0x9104016b	// add x11, x11, #0x100
	WORD	$0xc1588c84	// fmla za.s[w8, 4, vgx4], { z4.s - z7.s }, z8.s[3]
	WORD	$0xa040c16c	// ld1w { z12.s - z15.s }, pn8/z, [x11]
	WORD	$0x9104016b	// add x11, x11, #0x100
	WORD	$0xc1588d85	// fmla za.s[w8, 5, vgx4], { z12.s - z15.s }, z8.s[3]
	WORD	$0xa040c164	// ld1w { z4.s - z7.s }, pn8/z, [x11]
	WORD	$0x9104016b	// add x11, x11, #0x100
	WORD	$0xc1588c86	// fmla za.s[w8, 6, vgx4], { z4.s - z7.s }, z8.s[3]
	WORD	$0xa040c16c	// ld1w { z12.s - z15.s }, pn8/z, [x11]
	WORD	$0x9104016b	// add x11, x11, #0x100
	WORD	$0xc1588d87	// fmla za.s[w8, 7, vgx4], { z12.s - z15.s }, z8.s[3]
	WORD	$0x9100414a	// add x10, x10, #0x10
	WORD	$0x91001129	// add x9, x9, #0x4
	WORD	$0xeb05013f	// cmp x9, x5
	WORD	$0x54fff36b	// b.lt 0x50
	WORD	$0x14000023	// b 0x274
	WORD	$0x25a11521	// whilelt p1.s, x9, x1
	WORD	$0xa5002548	// ld1rqw { z8.s }, p1/z, [x10]
	WORD	$0x52800008	// mov w8, #0x0 ; =0
	WORD	$0xa040c164	// ld1w { z4.s - z7.s }, pn8/z, [x11]
	WORD	$0x9104016b	// add x11, x11, #0x100
	WORD	$0xc1588080	// fmla za.s[w8, 0, vgx4], { z4.s - z7.s }, z8.s[0]
	WORD	$0x11000508	// add w8, w8, #0x1
	WORD	$0xeb07011f	// cmp x8, x7
	WORD	$0x54ffff6b	// b.lt 0x1f8
	WORD	$0x52800008	// mov w8, #0x0 ; =0
	WORD	$0xa040c164	// ld1w { z4.s - z7.s }, pn8/z, [x11]
	WORD	$0x9104016b	// add x11, x11, #0x100
	WORD	$0xc1588480	// fmla za.s[w8, 0, vgx4], { z4.s - z7.s }, z8.s[1]
	WORD	$0x11000508	// add w8, w8, #0x1
	WORD	$0xeb07011f	// cmp x8, x7
	WORD	$0x54ffff6b	// b.lt 0x214
	WORD	$0x52800008	// mov w8, #0x0 ; =0
	WORD	$0xa040c164	// ld1w { z4.s - z7.s }, pn8/z, [x11]
	WORD	$0x9104016b	// add x11, x11, #0x100
	WORD	$0xc1588880	// fmla za.s[w8, 0, vgx4], { z4.s - z7.s }, z8.s[2]
	WORD	$0x11000508	// add w8, w8, #0x1
	WORD	$0xeb07011f	// cmp x8, x7
	WORD	$0x54ffff6b	// b.lt 0x230
	WORD	$0x52800008	// mov w8, #0x0 ; =0
	WORD	$0xa040c164	// ld1w { z4.s - z7.s }, pn8/z, [x11]
	WORD	$0x9104016b	// add x11, x11, #0x100
	WORD	$0xc1588c80	// fmla za.s[w8, 0, vgx4], { z4.s - z7.s }, z8.s[3]
	WORD	$0x11000508	// add w8, w8, #0x1
	WORD	$0xeb07011f	// cmp x8, x7
	WORD	$0x54ffff6b	// b.lt 0x24c
	WORD	$0x9100414a	// add x10, x10, #0x10
	WORD	$0x91001129	// add x9, x9, #0x4
	WORD	$0xeb05013f	// cmp x9, x5
	WORD	$0x54fffbeb	// b.lt 0x1ec
	WORD	$0x2598e3e3	// ptrue p3.s
	WORD	$0x65922fe4	// fcmeq p4.s, p3/z, z31.s, #0.0
	WORD	$0x2550cc80	// ptest p3, p4.b
	WORD	$0x54000141	// b.ne 0x2a8
	WORD	$0x25a08c09	// cntp x9, p3, p0.s
	WORD	$0xf100413f	// cmp x9, #0x10
	WORD	$0x540000e1	// b.ne 0x2a8
	WORD	$0x25a08709	// cntp x9, pn8.s, vlx4
	WORD	$0xf101013f	// cmp x9, #0x40
	WORD	$0x54000081	// b.ne 0x2a8
	WORD	$0x25608329	// cntp x9, pn9.h, vlx2
	WORD	$0xf101013f	// cmp x9, #0x40
	WORD	$0x540000c0	// b.eq 0x2bc
	WORD	$0x91000631	// add x17, x17, #0x1
	WORD	$0x2598e3e0	// ptrue p0.s
	WORD	$0x25a07810	// ptrue pn8.s
	WORD	$0x25607811	// ptrue pn9.h
	WORD	$0x17ffff5e	// b 0x30
	WORD	$0x25b9ce1f	// fmov z31.s, #1.00000000
	WORD	$0x52800008	// mov w8, #0x0 ; =0
	WORD	$0xaa0603e9	// mov x9, x6
	WORD	$0x8b06088a	// add x10, x4, x6, lsl #2
	WORD	$0xc0060c00	// mov { z0.d - z3.d }, za.d[w8, 0, vgx4]
	WORD	$0x25a36532	// whilelt pn10.s, x9, x3, vlx4
	WORD	$0xa060c940	// st1w { z0.s - z3.s }, pn10, [x10]
	WORD	$0x9104014a	// add x10, x10, #0x100
	WORD	$0x91010129	// add x9, x9, #0x40
	WORD	$0x11000508	// add w8, w8, #0x1
	WORD	$0xeb07011f	// cmp x8, x7
	WORD	$0x54ffff2b	// b.lt 0x2cc
	WORD	$0x2598e3e3	// ptrue p3.s
	WORD	$0x65922fe4	// fcmeq p4.s, p3/z, z31.s, #0.0
	WORD	$0x2550cc80	// ptest p3, p4.b
	WORD	$0x54000060	// b.eq 0x304
	WORD	$0x91000631	// add x17, x17, #0x1
	WORD	$0x17ffffef	// b 0x2bc
	WORD	$0x9b077ca9	// mul x9, x5, x7
	WORD	$0xd378dd29	// lsl x9, x9, #8
	WORD	$0x8b090210	// add x16, x16, x9
	WORD	$0x8b0718c6	// add x6, x6, x7, lsl #6
	WORD	$0xcb0701ad	// sub x13, x13, x7
	WORD	$0xb5ffe86d	// cbnz x13, 0x24
	WORD	$0xd503467f	// smstop
	WORD	$0xaa1103e0	// mov x0, x17
	MOVD	R0, retries+48(FP)
	RET

// func smeVectorF16(x *float32, k int, w *uint16, n int, y *float32, kp int) (retries int)
TEXT ·smeVectorF16(SB), NOSPLIT, $0-56
	MOVD	x+0(FP), R0
	MOVD	k+8(FP), R1
	MOVD	w+16(FP), R2
	MOVD	n+24(FP), R3
	MOVD	y+32(FP), R4
	MOVD	kp+40(FP), R5
	WORD	$0xd503477f	// smstart
	WORD	$0x2598e3e0	// ptrue p0.s
	WORD	$0x25a07810	// ptrue pn8.s
	WORD	$0x25607811	// ptrue pn9.h
	WORD	$0xd2800011	// mov x17, #0x0 ; =0
	WORD	$0x9100fc6d	// add x13, x3, #0x3f
	WORD	$0xd346fdad	// lsr x13, x13, #6
	WORD	$0xd2800006	// mov x6, #0x0 ; =0
	WORD	$0xaa0203f0	// mov x16, x2
	WORD	$0xd2800107	// mov x7, #0x8 ; =8
	WORD	$0xf10021bf	// cmp x13, #0x8
	WORD	$0x9a87b1a7	// csel x7, x13, x7, lt
	WORD	$0xc00800ff	// zero {za}
	WORD	$0x25b9ce1f	// fmov z31.s, #1.00000000
	WORD	$0xd2800009	// mov x9, #0x0 ; =0
	WORD	$0xaa0003ea	// mov x10, x0
	WORD	$0xaa1003eb	// mov x11, x16
	WORD	$0x52800008	// mov w8, #0x0 ; =0
	WORD	$0xf10020ff	// cmp x7, #0x8
	WORD	$0x54001d01	// b.ne 0x3ec
	WORD	$0x25a11521	// whilelt p1.s, x9, x1
	WORD	$0xa5002548	// ld1rqw { z8.s }, p1/z, [x10]
	WORD	$0xa0402560	// ld1h { z0.h, z1.h }, pn9/z, [x11]
	WORD	$0x9102016b	// add x11, x11, #0x80
	WORD	$0x6589a004	// fcvt z4.s, p0/m, z0.h
	WORD	$0x6489a005	// fcvtlt z5.s, p0/m, z0.h
	WORD	$0x6589a026	// fcvt z6.s, p0/m, z1.h
	WORD	$0x6489a027	// fcvtlt z7.s, p0/m, z1.h
	WORD	$0xc1588080	// fmla za.s[w8, 0, vgx4], { z4.s - z7.s }, z8.s[0]
	WORD	$0xa0402562	// ld1h { z2.h, z3.h }, pn9/z, [x11]
	WORD	$0x9102016b	// add x11, x11, #0x80
	WORD	$0x6589a04c	// fcvt z12.s, p0/m, z2.h
	WORD	$0x6489a04d	// fcvtlt z13.s, p0/m, z2.h
	WORD	$0x6589a06e	// fcvt z14.s, p0/m, z3.h
	WORD	$0x6489a06f	// fcvtlt z15.s, p0/m, z3.h
	WORD	$0xc1588181	// fmla za.s[w8, 1, vgx4], { z12.s - z15.s }, z8.s[0]
	WORD	$0xa0402560	// ld1h { z0.h, z1.h }, pn9/z, [x11]
	WORD	$0x9102016b	// add x11, x11, #0x80
	WORD	$0x6589a004	// fcvt z4.s, p0/m, z0.h
	WORD	$0x6489a005	// fcvtlt z5.s, p0/m, z0.h
	WORD	$0x6589a026	// fcvt z6.s, p0/m, z1.h
	WORD	$0x6489a027	// fcvtlt z7.s, p0/m, z1.h
	WORD	$0xc1588082	// fmla za.s[w8, 2, vgx4], { z4.s - z7.s }, z8.s[0]
	WORD	$0xa0402562	// ld1h { z2.h, z3.h }, pn9/z, [x11]
	WORD	$0x9102016b	// add x11, x11, #0x80
	WORD	$0x6589a04c	// fcvt z12.s, p0/m, z2.h
	WORD	$0x6489a04d	// fcvtlt z13.s, p0/m, z2.h
	WORD	$0x6589a06e	// fcvt z14.s, p0/m, z3.h
	WORD	$0x6489a06f	// fcvtlt z15.s, p0/m, z3.h
	WORD	$0xc1588183	// fmla za.s[w8, 3, vgx4], { z12.s - z15.s }, z8.s[0]
	WORD	$0xa0402560	// ld1h { z0.h, z1.h }, pn9/z, [x11]
	WORD	$0x9102016b	// add x11, x11, #0x80
	WORD	$0x6589a004	// fcvt z4.s, p0/m, z0.h
	WORD	$0x6489a005	// fcvtlt z5.s, p0/m, z0.h
	WORD	$0x6589a026	// fcvt z6.s, p0/m, z1.h
	WORD	$0x6489a027	// fcvtlt z7.s, p0/m, z1.h
	WORD	$0xc1588084	// fmla za.s[w8, 4, vgx4], { z4.s - z7.s }, z8.s[0]
	WORD	$0xa0402562	// ld1h { z2.h, z3.h }, pn9/z, [x11]
	WORD	$0x9102016b	// add x11, x11, #0x80
	WORD	$0x6589a04c	// fcvt z12.s, p0/m, z2.h
	WORD	$0x6489a04d	// fcvtlt z13.s, p0/m, z2.h
	WORD	$0x6589a06e	// fcvt z14.s, p0/m, z3.h
	WORD	$0x6489a06f	// fcvtlt z15.s, p0/m, z3.h
	WORD	$0xc1588185	// fmla za.s[w8, 5, vgx4], { z12.s - z15.s }, z8.s[0]
	WORD	$0xa0402560	// ld1h { z0.h, z1.h }, pn9/z, [x11]
	WORD	$0x9102016b	// add x11, x11, #0x80
	WORD	$0x6589a004	// fcvt z4.s, p0/m, z0.h
	WORD	$0x6489a005	// fcvtlt z5.s, p0/m, z0.h
	WORD	$0x6589a026	// fcvt z6.s, p0/m, z1.h
	WORD	$0x6489a027	// fcvtlt z7.s, p0/m, z1.h
	WORD	$0xc1588086	// fmla za.s[w8, 6, vgx4], { z4.s - z7.s }, z8.s[0]
	WORD	$0xa0402562	// ld1h { z2.h, z3.h }, pn9/z, [x11]
	WORD	$0x9102016b	// add x11, x11, #0x80
	WORD	$0x6589a04c	// fcvt z12.s, p0/m, z2.h
	WORD	$0x6489a04d	// fcvtlt z13.s, p0/m, z2.h
	WORD	$0x6589a06e	// fcvt z14.s, p0/m, z3.h
	WORD	$0x6489a06f	// fcvtlt z15.s, p0/m, z3.h
	WORD	$0xc1588187	// fmla za.s[w8, 7, vgx4], { z12.s - z15.s }, z8.s[0]
	WORD	$0xa0402560	// ld1h { z0.h, z1.h }, pn9/z, [x11]
	WORD	$0x9102016b	// add x11, x11, #0x80
	WORD	$0x6589a004	// fcvt z4.s, p0/m, z0.h
	WORD	$0x6489a005	// fcvtlt z5.s, p0/m, z0.h
	WORD	$0x6589a026	// fcvt z6.s, p0/m, z1.h
	WORD	$0x6489a027	// fcvtlt z7.s, p0/m, z1.h
	WORD	$0xc1588480	// fmla za.s[w8, 0, vgx4], { z4.s - z7.s }, z8.s[1]
	WORD	$0xa0402562	// ld1h { z2.h, z3.h }, pn9/z, [x11]
	WORD	$0x9102016b	// add x11, x11, #0x80
	WORD	$0x6589a04c	// fcvt z12.s, p0/m, z2.h
	WORD	$0x6489a04d	// fcvtlt z13.s, p0/m, z2.h
	WORD	$0x6589a06e	// fcvt z14.s, p0/m, z3.h
	WORD	$0x6489a06f	// fcvtlt z15.s, p0/m, z3.h
	WORD	$0xc1588581	// fmla za.s[w8, 1, vgx4], { z12.s - z15.s }, z8.s[1]
	WORD	$0xa0402560	// ld1h { z0.h, z1.h }, pn9/z, [x11]
	WORD	$0x9102016b	// add x11, x11, #0x80
	WORD	$0x6589a004	// fcvt z4.s, p0/m, z0.h
	WORD	$0x6489a005	// fcvtlt z5.s, p0/m, z0.h
	WORD	$0x6589a026	// fcvt z6.s, p0/m, z1.h
	WORD	$0x6489a027	// fcvtlt z7.s, p0/m, z1.h
	WORD	$0xc1588482	// fmla za.s[w8, 2, vgx4], { z4.s - z7.s }, z8.s[1]
	WORD	$0xa0402562	// ld1h { z2.h, z3.h }, pn9/z, [x11]
	WORD	$0x9102016b	// add x11, x11, #0x80
	WORD	$0x6589a04c	// fcvt z12.s, p0/m, z2.h
	WORD	$0x6489a04d	// fcvtlt z13.s, p0/m, z2.h
	WORD	$0x6589a06e	// fcvt z14.s, p0/m, z3.h
	WORD	$0x6489a06f	// fcvtlt z15.s, p0/m, z3.h
	WORD	$0xc1588583	// fmla za.s[w8, 3, vgx4], { z12.s - z15.s }, z8.s[1]
	WORD	$0xa0402560	// ld1h { z0.h, z1.h }, pn9/z, [x11]
	WORD	$0x9102016b	// add x11, x11, #0x80
	WORD	$0x6589a004	// fcvt z4.s, p0/m, z0.h
	WORD	$0x6489a005	// fcvtlt z5.s, p0/m, z0.h
	WORD	$0x6589a026	// fcvt z6.s, p0/m, z1.h
	WORD	$0x6489a027	// fcvtlt z7.s, p0/m, z1.h
	WORD	$0xc1588484	// fmla za.s[w8, 4, vgx4], { z4.s - z7.s }, z8.s[1]
	WORD	$0xa0402562	// ld1h { z2.h, z3.h }, pn9/z, [x11]
	WORD	$0x9102016b	// add x11, x11, #0x80
	WORD	$0x6589a04c	// fcvt z12.s, p0/m, z2.h
	WORD	$0x6489a04d	// fcvtlt z13.s, p0/m, z2.h
	WORD	$0x6589a06e	// fcvt z14.s, p0/m, z3.h
	WORD	$0x6489a06f	// fcvtlt z15.s, p0/m, z3.h
	WORD	$0xc1588585	// fmla za.s[w8, 5, vgx4], { z12.s - z15.s }, z8.s[1]
	WORD	$0xa0402560	// ld1h { z0.h, z1.h }, pn9/z, [x11]
	WORD	$0x9102016b	// add x11, x11, #0x80
	WORD	$0x6589a004	// fcvt z4.s, p0/m, z0.h
	WORD	$0x6489a005	// fcvtlt z5.s, p0/m, z0.h
	WORD	$0x6589a026	// fcvt z6.s, p0/m, z1.h
	WORD	$0x6489a027	// fcvtlt z7.s, p0/m, z1.h
	WORD	$0xc1588486	// fmla za.s[w8, 6, vgx4], { z4.s - z7.s }, z8.s[1]
	WORD	$0xa0402562	// ld1h { z2.h, z3.h }, pn9/z, [x11]
	WORD	$0x9102016b	// add x11, x11, #0x80
	WORD	$0x6589a04c	// fcvt z12.s, p0/m, z2.h
	WORD	$0x6489a04d	// fcvtlt z13.s, p0/m, z2.h
	WORD	$0x6589a06e	// fcvt z14.s, p0/m, z3.h
	WORD	$0x6489a06f	// fcvtlt z15.s, p0/m, z3.h
	WORD	$0xc1588587	// fmla za.s[w8, 7, vgx4], { z12.s - z15.s }, z8.s[1]
	WORD	$0xa0402560	// ld1h { z0.h, z1.h }, pn9/z, [x11]
	WORD	$0x9102016b	// add x11, x11, #0x80
	WORD	$0x6589a004	// fcvt z4.s, p0/m, z0.h
	WORD	$0x6489a005	// fcvtlt z5.s, p0/m, z0.h
	WORD	$0x6589a026	// fcvt z6.s, p0/m, z1.h
	WORD	$0x6489a027	// fcvtlt z7.s, p0/m, z1.h
	WORD	$0xc1588880	// fmla za.s[w8, 0, vgx4], { z4.s - z7.s }, z8.s[2]
	WORD	$0xa0402562	// ld1h { z2.h, z3.h }, pn9/z, [x11]
	WORD	$0x9102016b	// add x11, x11, #0x80
	WORD	$0x6589a04c	// fcvt z12.s, p0/m, z2.h
	WORD	$0x6489a04d	// fcvtlt z13.s, p0/m, z2.h
	WORD	$0x6589a06e	// fcvt z14.s, p0/m, z3.h
	WORD	$0x6489a06f	// fcvtlt z15.s, p0/m, z3.h
	WORD	$0xc1588981	// fmla za.s[w8, 1, vgx4], { z12.s - z15.s }, z8.s[2]
	WORD	$0xa0402560	// ld1h { z0.h, z1.h }, pn9/z, [x11]
	WORD	$0x9102016b	// add x11, x11, #0x80
	WORD	$0x6589a004	// fcvt z4.s, p0/m, z0.h
	WORD	$0x6489a005	// fcvtlt z5.s, p0/m, z0.h
	WORD	$0x6589a026	// fcvt z6.s, p0/m, z1.h
	WORD	$0x6489a027	// fcvtlt z7.s, p0/m, z1.h
	WORD	$0xc1588882	// fmla za.s[w8, 2, vgx4], { z4.s - z7.s }, z8.s[2]
	WORD	$0xa0402562	// ld1h { z2.h, z3.h }, pn9/z, [x11]
	WORD	$0x9102016b	// add x11, x11, #0x80
	WORD	$0x6589a04c	// fcvt z12.s, p0/m, z2.h
	WORD	$0x6489a04d	// fcvtlt z13.s, p0/m, z2.h
	WORD	$0x6589a06e	// fcvt z14.s, p0/m, z3.h
	WORD	$0x6489a06f	// fcvtlt z15.s, p0/m, z3.h
	WORD	$0xc1588983	// fmla za.s[w8, 3, vgx4], { z12.s - z15.s }, z8.s[2]
	WORD	$0xa0402560	// ld1h { z0.h, z1.h }, pn9/z, [x11]
	WORD	$0x9102016b	// add x11, x11, #0x80
	WORD	$0x6589a004	// fcvt z4.s, p0/m, z0.h
	WORD	$0x6489a005	// fcvtlt z5.s, p0/m, z0.h
	WORD	$0x6589a026	// fcvt z6.s, p0/m, z1.h
	WORD	$0x6489a027	// fcvtlt z7.s, p0/m, z1.h
	WORD	$0xc1588884	// fmla za.s[w8, 4, vgx4], { z4.s - z7.s }, z8.s[2]
	WORD	$0xa0402562	// ld1h { z2.h, z3.h }, pn9/z, [x11]
	WORD	$0x9102016b	// add x11, x11, #0x80
	WORD	$0x6589a04c	// fcvt z12.s, p0/m, z2.h
	WORD	$0x6489a04d	// fcvtlt z13.s, p0/m, z2.h
	WORD	$0x6589a06e	// fcvt z14.s, p0/m, z3.h
	WORD	$0x6489a06f	// fcvtlt z15.s, p0/m, z3.h
	WORD	$0xc1588985	// fmla za.s[w8, 5, vgx4], { z12.s - z15.s }, z8.s[2]
	WORD	$0xa0402560	// ld1h { z0.h, z1.h }, pn9/z, [x11]
	WORD	$0x9102016b	// add x11, x11, #0x80
	WORD	$0x6589a004	// fcvt z4.s, p0/m, z0.h
	WORD	$0x6489a005	// fcvtlt z5.s, p0/m, z0.h
	WORD	$0x6589a026	// fcvt z6.s, p0/m, z1.h
	WORD	$0x6489a027	// fcvtlt z7.s, p0/m, z1.h
	WORD	$0xc1588886	// fmla za.s[w8, 6, vgx4], { z4.s - z7.s }, z8.s[2]
	WORD	$0xa0402562	// ld1h { z2.h, z3.h }, pn9/z, [x11]
	WORD	$0x9102016b	// add x11, x11, #0x80
	WORD	$0x6589a04c	// fcvt z12.s, p0/m, z2.h
	WORD	$0x6489a04d	// fcvtlt z13.s, p0/m, z2.h
	WORD	$0x6589a06e	// fcvt z14.s, p0/m, z3.h
	WORD	$0x6489a06f	// fcvtlt z15.s, p0/m, z3.h
	WORD	$0xc1588987	// fmla za.s[w8, 7, vgx4], { z12.s - z15.s }, z8.s[2]
	WORD	$0xa0402560	// ld1h { z0.h, z1.h }, pn9/z, [x11]
	WORD	$0x9102016b	// add x11, x11, #0x80
	WORD	$0x6589a004	// fcvt z4.s, p0/m, z0.h
	WORD	$0x6489a005	// fcvtlt z5.s, p0/m, z0.h
	WORD	$0x6589a026	// fcvt z6.s, p0/m, z1.h
	WORD	$0x6489a027	// fcvtlt z7.s, p0/m, z1.h
	WORD	$0xc1588c80	// fmla za.s[w8, 0, vgx4], { z4.s - z7.s }, z8.s[3]
	WORD	$0xa0402562	// ld1h { z2.h, z3.h }, pn9/z, [x11]
	WORD	$0x9102016b	// add x11, x11, #0x80
	WORD	$0x6589a04c	// fcvt z12.s, p0/m, z2.h
	WORD	$0x6489a04d	// fcvtlt z13.s, p0/m, z2.h
	WORD	$0x6589a06e	// fcvt z14.s, p0/m, z3.h
	WORD	$0x6489a06f	// fcvtlt z15.s, p0/m, z3.h
	WORD	$0xc1588d81	// fmla za.s[w8, 1, vgx4], { z12.s - z15.s }, z8.s[3]
	WORD	$0xa0402560	// ld1h { z0.h, z1.h }, pn9/z, [x11]
	WORD	$0x9102016b	// add x11, x11, #0x80
	WORD	$0x6589a004	// fcvt z4.s, p0/m, z0.h
	WORD	$0x6489a005	// fcvtlt z5.s, p0/m, z0.h
	WORD	$0x6589a026	// fcvt z6.s, p0/m, z1.h
	WORD	$0x6489a027	// fcvtlt z7.s, p0/m, z1.h
	WORD	$0xc1588c82	// fmla za.s[w8, 2, vgx4], { z4.s - z7.s }, z8.s[3]
	WORD	$0xa0402562	// ld1h { z2.h, z3.h }, pn9/z, [x11]
	WORD	$0x9102016b	// add x11, x11, #0x80
	WORD	$0x6589a04c	// fcvt z12.s, p0/m, z2.h
	WORD	$0x6489a04d	// fcvtlt z13.s, p0/m, z2.h
	WORD	$0x6589a06e	// fcvt z14.s, p0/m, z3.h
	WORD	$0x6489a06f	// fcvtlt z15.s, p0/m, z3.h
	WORD	$0xc1588d83	// fmla za.s[w8, 3, vgx4], { z12.s - z15.s }, z8.s[3]
	WORD	$0xa0402560	// ld1h { z0.h, z1.h }, pn9/z, [x11]
	WORD	$0x9102016b	// add x11, x11, #0x80
	WORD	$0x6589a004	// fcvt z4.s, p0/m, z0.h
	WORD	$0x6489a005	// fcvtlt z5.s, p0/m, z0.h
	WORD	$0x6589a026	// fcvt z6.s, p0/m, z1.h
	WORD	$0x6489a027	// fcvtlt z7.s, p0/m, z1.h
	WORD	$0xc1588c84	// fmla za.s[w8, 4, vgx4], { z4.s - z7.s }, z8.s[3]
	WORD	$0xa0402562	// ld1h { z2.h, z3.h }, pn9/z, [x11]
	WORD	$0x9102016b	// add x11, x11, #0x80
	WORD	$0x6589a04c	// fcvt z12.s, p0/m, z2.h
	WORD	$0x6489a04d	// fcvtlt z13.s, p0/m, z2.h
	WORD	$0x6589a06e	// fcvt z14.s, p0/m, z3.h
	WORD	$0x6489a06f	// fcvtlt z15.s, p0/m, z3.h
	WORD	$0xc1588d85	// fmla za.s[w8, 5, vgx4], { z12.s - z15.s }, z8.s[3]
	WORD	$0xa0402560	// ld1h { z0.h, z1.h }, pn9/z, [x11]
	WORD	$0x9102016b	// add x11, x11, #0x80
	WORD	$0x6589a004	// fcvt z4.s, p0/m, z0.h
	WORD	$0x6489a005	// fcvtlt z5.s, p0/m, z0.h
	WORD	$0x6589a026	// fcvt z6.s, p0/m, z1.h
	WORD	$0x6489a027	// fcvtlt z7.s, p0/m, z1.h
	WORD	$0xc1588c86	// fmla za.s[w8, 6, vgx4], { z4.s - z7.s }, z8.s[3]
	WORD	$0xa0402562	// ld1h { z2.h, z3.h }, pn9/z, [x11]
	WORD	$0x9102016b	// add x11, x11, #0x80
	WORD	$0x6589a04c	// fcvt z12.s, p0/m, z2.h
	WORD	$0x6489a04d	// fcvtlt z13.s, p0/m, z2.h
	WORD	$0x6589a06e	// fcvt z14.s, p0/m, z3.h
	WORD	$0x6489a06f	// fcvtlt z15.s, p0/m, z3.h
	WORD	$0xc1588d87	// fmla za.s[w8, 7, vgx4], { z12.s - z15.s }, z8.s[3]
	WORD	$0x9100414a	// add x10, x10, #0x10
	WORD	$0x91001129	// add x9, x9, #0x4
	WORD	$0xeb05013f	// cmp x9, x5
	WORD	$0x54ffe36b	// b.lt 0x50
	WORD	$0x14000033	// b 0x4b4
	WORD	$0x25a11521	// whilelt p1.s, x9, x1
	WORD	$0xa5002548	// ld1rqw { z8.s }, p1/z, [x10]
	WORD	$0x52800008	// mov w8, #0x0 ; =0
	WORD	$0xa0402560	// ld1h { z0.h, z1.h }, pn9/z, [x11]
	WORD	$0x9102016b	// add x11, x11, #0x80
	WORD	$0x6589a004	// fcvt z4.s, p0/m, z0.h
	WORD	$0x6489a005	// fcvtlt z5.s, p0/m, z0.h
	WORD	$0x6589a026	// fcvt z6.s, p0/m, z1.h
	WORD	$0x6489a027	// fcvtlt z7.s, p0/m, z1.h
	WORD	$0xc1588080	// fmla za.s[w8, 0, vgx4], { z4.s - z7.s }, z8.s[0]
	WORD	$0x11000508	// add w8, w8, #0x1
	WORD	$0xeb07011f	// cmp x8, x7
	WORD	$0x54fffeeb	// b.lt 0x3f8
	WORD	$0x52800008	// mov w8, #0x0 ; =0
	WORD	$0xa0402560	// ld1h { z0.h, z1.h }, pn9/z, [x11]
	WORD	$0x9102016b	// add x11, x11, #0x80
	WORD	$0x6589a004	// fcvt z4.s, p0/m, z0.h
	WORD	$0x6489a005	// fcvtlt z5.s, p0/m, z0.h
	WORD	$0x6589a026	// fcvt z6.s, p0/m, z1.h
	WORD	$0x6489a027	// fcvtlt z7.s, p0/m, z1.h
	WORD	$0xc1588480	// fmla za.s[w8, 0, vgx4], { z4.s - z7.s }, z8.s[1]
	WORD	$0x11000508	// add w8, w8, #0x1
	WORD	$0xeb07011f	// cmp x8, x7
	WORD	$0x54fffeeb	// b.lt 0x424
	WORD	$0x52800008	// mov w8, #0x0 ; =0
	WORD	$0xa0402560	// ld1h { z0.h, z1.h }, pn9/z, [x11]
	WORD	$0x9102016b	// add x11, x11, #0x80
	WORD	$0x6589a004	// fcvt z4.s, p0/m, z0.h
	WORD	$0x6489a005	// fcvtlt z5.s, p0/m, z0.h
	WORD	$0x6589a026	// fcvt z6.s, p0/m, z1.h
	WORD	$0x6489a027	// fcvtlt z7.s, p0/m, z1.h
	WORD	$0xc1588880	// fmla za.s[w8, 0, vgx4], { z4.s - z7.s }, z8.s[2]
	WORD	$0x11000508	// add w8, w8, #0x1
	WORD	$0xeb07011f	// cmp x8, x7
	WORD	$0x54fffeeb	// b.lt 0x450
	WORD	$0x52800008	// mov w8, #0x0 ; =0
	WORD	$0xa0402560	// ld1h { z0.h, z1.h }, pn9/z, [x11]
	WORD	$0x9102016b	// add x11, x11, #0x80
	WORD	$0x6589a004	// fcvt z4.s, p0/m, z0.h
	WORD	$0x6489a005	// fcvtlt z5.s, p0/m, z0.h
	WORD	$0x6589a026	// fcvt z6.s, p0/m, z1.h
	WORD	$0x6489a027	// fcvtlt z7.s, p0/m, z1.h
	WORD	$0xc1588c80	// fmla za.s[w8, 0, vgx4], { z4.s - z7.s }, z8.s[3]
	WORD	$0x11000508	// add w8, w8, #0x1
	WORD	$0xeb07011f	// cmp x8, x7
	WORD	$0x54fffeeb	// b.lt 0x47c
	WORD	$0x9100414a	// add x10, x10, #0x10
	WORD	$0x91001129	// add x9, x9, #0x4
	WORD	$0xeb05013f	// cmp x9, x5
	WORD	$0x54fff9eb	// b.lt 0x3ec
	WORD	$0x2598e3e3	// ptrue p3.s
	WORD	$0x65922fe4	// fcmeq p4.s, p3/z, z31.s, #0.0
	WORD	$0x2550cc80	// ptest p3, p4.b
	WORD	$0x54000141	// b.ne 0x4e8
	WORD	$0x25a08c09	// cntp x9, p3, p0.s
	WORD	$0xf100413f	// cmp x9, #0x10
	WORD	$0x540000e1	// b.ne 0x4e8
	WORD	$0x25a08709	// cntp x9, pn8.s, vlx4
	WORD	$0xf101013f	// cmp x9, #0x40
	WORD	$0x54000081	// b.ne 0x4e8
	WORD	$0x25608329	// cntp x9, pn9.h, vlx2
	WORD	$0xf101013f	// cmp x9, #0x40
	WORD	$0x540000c0	// b.eq 0x4fc
	WORD	$0x91000631	// add x17, x17, #0x1
	WORD	$0x2598e3e0	// ptrue p0.s
	WORD	$0x25a07810	// ptrue pn8.s
	WORD	$0x25607811	// ptrue pn9.h
	WORD	$0x17fffece	// b 0x30
	WORD	$0x25b9ce1f	// fmov z31.s, #1.00000000
	WORD	$0x52800008	// mov w8, #0x0 ; =0
	WORD	$0xaa0603e9	// mov x9, x6
	WORD	$0x8b06088a	// add x10, x4, x6, lsl #2
	WORD	$0xc0060c00	// mov { z0.d - z3.d }, za.d[w8, 0, vgx4]
	WORD	$0x25a36532	// whilelt pn10.s, x9, x3, vlx4
	WORD	$0xa060c940	// st1w { z0.s - z3.s }, pn10, [x10]
	WORD	$0x9104014a	// add x10, x10, #0x100
	WORD	$0x91010129	// add x9, x9, #0x40
	WORD	$0x11000508	// add w8, w8, #0x1
	WORD	$0xeb07011f	// cmp x8, x7
	WORD	$0x54ffff2b	// b.lt 0x50c
	WORD	$0x2598e3e3	// ptrue p3.s
	WORD	$0x65922fe4	// fcmeq p4.s, p3/z, z31.s, #0.0
	WORD	$0x2550cc80	// ptest p3, p4.b
	WORD	$0x54000060	// b.eq 0x544
	WORD	$0x91000631	// add x17, x17, #0x1
	WORD	$0x17ffffef	// b 0x4fc
	WORD	$0x9b077ca9	// mul x9, x5, x7
	WORD	$0xd379e129	// lsl x9, x9, #7
	WORD	$0x8b090210	// add x16, x16, x9
	WORD	$0x8b0718c6	// add x6, x6, x7, lsl #6
	WORD	$0xcb0701ad	// sub x13, x13, x7
	WORD	$0xb5ffd66d	// cbnz x13, 0x24
	WORD	$0xd503467f	// smstop
	WORD	$0xaa1103e0	// mov x0, x17
	MOVD	R0, retries+48(FP)
	RET

// func smeVectorBytes() int
TEXT ·smeVectorBytes(SB), NOSPLIT, $0-8
	WORD	$0x04bf5820	// rdsvl x0, #1
	MOVD	R0, ret+0(FP)
	RET
