#!/usr/bin/env python3
"""Generate the Go WORD encoding for the SME tile sources."""
import os, subprocess, sys

here = os.path.dirname(os.path.abspath(__file__))
os.chdir(here)


def words(src):
    return subprocess.check_output([sys.executable, "gen.py", src]).decode()


def args(names, _retoff):
    lines = []
    for i, (name, reg) in enumerate(names):
        lines.append("\tMOVD\t%s+%d(FP), %s\n" % (name, 8 * i, reg))
    return lines


out = [
    "// Code generated by smesrc/build.py; DO NOT EDIT.\n\n",
    "//go:build arm64\n\n#include \"textflag.h\"\n\n",
    "// func smeMulF16(q *int8, kPairs, panels int, activation *uint16, dst *float32, cols, rows, strideBytes int, colScales, rowScales *float32) (retries int)\n",
    "TEXT ·smeMulF16(SB), NOSPLIT, $0-88\n",
]
out += args([("q", "R0"), ("kPairs", "R1"), ("panels", "R2"), ("activation", "R3"),
             ("dst", "R4"), ("cols", "R5"), ("rows", "R6"), ("strideBytes", "R7"),
             ("colScales", "R16"), ("rowScales", "R19")], 80)
out += [words("tile16x64h.S"), "\tMOVD\tR0, retries+80(FP)\n", "\tRET\n\n"]
out += [
    "// func smeMulF16W(w *uint16, kPairs, panels int, activation *uint16, dst *float32, cols, rows, strideBytes int, colScales, rowScales *float32) (retries int)\n",
    "TEXT ·smeMulF16W(SB), NOSPLIT, $0-88\n",
]
out += args([("w", "R0"), ("kPairs", "R1"), ("panels", "R2"), ("activation", "R3"),
             ("dst", "R4"), ("cols", "R5"), ("rows", "R6"), ("strideBytes", "R7"),
             ("colScales", "R16"), ("rowScales", "R19")], 80)
out += [words("tile16x64hh.S"), "\tMOVD\tR0, retries+80(FP)\n", "\tRET\n\n"]
out += [
    "// func smeVectorBytes() int\n",
    "TEXT ·smeVectorBytes(SB), NOSPLIT, $0-8\n",
    "\tWORD\t$0x04bf5820\t// rdsvl x0, #1\n",
    "\tMOVD\tR0, ret+0(FP)\n",
    "\tRET\n",
]
root = os.path.dirname(here)
with open(os.path.join(root, "sme_arm64.s"), "w") as f:
    f.writelines(out)

neon = [
    "// Code generated by smesrc/build.py; DO NOT EDIT.\n\n",
    "//go:build arm64\n\n#include \"textflag.h\"\n\n",
    "// func packPairsNEON(dst *uint16, src *float32, pairs int, scale float32)\n",
    "TEXT ·packPairsNEON(SB), NOSPLIT, $0-28\n",
    "\tMOVD\tdst+0(FP), R0\n",
    "\tMOVD\tsrc+8(FP), R1\n",
    "\tMOVD\tpairs+16(FP), R2\n",
    "\tFMOVS\tscale+24(FP), F0\n",
    words("packpairs.S"),
    "\tRET\n\n",
    "// func maxAbsNEON(src *float32, n int) float32\n",
    "TEXT ·maxAbsNEON(SB), NOSPLIT, $0-20\n",
    "\tMOVD\tsrc+0(FP), R0\n",
    "\tMOVD\tn+8(FP), R1\n",
    words("maxabs.S"),
    "\tFMOVS\tF0, ret+16(FP)\n",
    "\tRET\n",
]
with open(os.path.join(root, "neon_arm64.s"), "w") as f:
    f.writelines(neon)
