#!/usr/bin/env python3
"""Generate the Go WORD encoding for the SME tile source."""
import os, subprocess, sys

here = os.path.dirname(os.path.abspath(__file__))
os.chdir(here)
words = subprocess.check_output([sys.executable, "gen.py", "tile16x64.S"]).decode()
out = [
    "// Code generated by smesrc/build.py; DO NOT EDIT.\n\n",
    "//go:build arm64\n\n#include \"textflag.h\"\n\n",
    "// func smeMul16x64(q *int8, k, panels int, activation *float32, dst *float32, n, rows int) (retries int)\n",
    "TEXT ·smeMul16x64(SB), NOSPLIT, $0-64\n",
    "\tMOVD\tq+0(FP), R0\n",
    "\tMOVD\tk+8(FP), R1\n",
    "\tMOVD\tpanels+16(FP), R2\n",
    "\tMOVD\tactivation+24(FP), R3\n",
    "\tMOVD\tdst+32(FP), R4\n",
    "\tMOVD\tn+40(FP), R5\n",
    "\tMOVD\trows+48(FP), R6\n",
    words,
    "\tMOVD\tR0, retries+56(FP)\n",
    "\tRET\n\n",
    "// func smeVectorBytes() int\n",
    "TEXT ·smeVectorBytes(SB), NOSPLIT, $0-8\n",
    "\tWORD\t$0x04bf5820\t// rdsvl x0, #1\n",
    "\tMOVD\tR0, ret+0(FP)\n",
    "\tRET\n",
]
root = os.path.dirname(here)
with open(os.path.join(root, "sme_arm64.s"), "w") as f:
    f.writelines(out)
