// Code generated by smesrc/build.py; DO NOT EDIT.

//go:build arm64

#include "textflag.h"

// func packPairsNEON(dst *uint16, src *float32, pairs int, scale float32)
TEXT ·packPairsNEON(SB), NOSPLIT, $0-28
	MOVD	dst+0(FP), R0
	MOVD	src+8(FP), R1
	MOVD	pairs+16(FP), R2
	FMOVS	scale+24(FP), F0
	WORD	$0x4e04041f	// dup.4s v31, v0[0]
	WORD	$0xd2800803	// mov x3, #0x40 ; =64
	WORD	$0xf100105f	// cmp x2, #0x4
	WORD	$0x5400018b	// b.lt 0x3c
	WORD	$0x4cdfa820	// ld1.4s { v0, v1 }, [x1], #32
	WORD	$0x6e3fdc00	// fmul.4s v0, v0, v31
	WORD	$0x6e3fdc21	// fmul.4s v1, v1, v31
	WORD	$0x0e216802	// fcvtn v2.4h, v0.4s
	WORD	$0x4e216822	// fcvtn2 v2.8h, v1.4s
	WORD	$0x0d838002	// st1.s { v2 }[0], [x0], x3
	WORD	$0x0d839002	// st1.s { v2 }[1], [x0], x3
	WORD	$0x4d838002	// st1.s { v2 }[2], [x0], x3
	WORD	$0x4d839002	// st1.s { v2 }[3], [x0], x3
	WORD	$0xd1001042	// sub x2, x2, #0x4
	WORD	$0x17fffff4	// b 0x8
	RET

// func maxAbsNEON(src *float32, n int) float32
TEXT ·maxAbsNEON(SB), NOSPLIT, $0-20
	MOVD	src+0(FP), R0
	MOVD	n+8(FP), R1
	WORD	$0x4f000400	// movi.4s v0, #0x0
	WORD	$0x4f000401	// movi.4s v1, #0x0
	WORD	$0x4f000402	// movi.4s v2, #0x0
	WORD	$0x4f000403	// movi.4s v3, #0x0
	WORD	$0xf100403f	// cmp x1, #0x10
	WORD	$0x5400018b	// b.lt 0x44
	WORD	$0x4cdf2804	// ld1.4s { v4, v5, v6, v7 }, [x0], #64
	WORD	$0x4ea0f884	// fabs.4s v4, v4
	WORD	$0x4ea0f8a5	// fabs.4s v5, v5
	WORD	$0x4ea0f8c6	// fabs.4s v6, v6
	WORD	$0x4ea0f8e7	// fabs.4s v7, v7
	WORD	$0x4e24f400	// fmax.4s v0, v0, v4
	WORD	$0x4e25f421	// fmax.4s v1, v1, v5
	WORD	$0x4e26f442	// fmax.4s v2, v2, v6
	WORD	$0x4e27f463	// fmax.4s v3, v3, v7
	WORD	$0xd1004021	// sub x1, x1, #0x10
	WORD	$0x17fffff4	// b 0x10
	WORD	$0x4e21f400	// fmax.4s v0, v0, v1
	WORD	$0x4e23f442	// fmax.4s v2, v2, v3
	WORD	$0x4e22f400	// fmax.4s v0, v0, v2
	WORD	$0x6e30f800	// fmaxv.4s s0, v0
	FMOVS	F0, ret+16(FP)
	RET
