// Code generated by smesrc/build.py; DO NOT EDIT.

//go:build arm64

#include "textflag.h"

// func smeMul16x64(q *int8, k, panels int, activation *float32, dst *float32, n, rows int) (retries int)
TEXT ·smeMul16x64(SB), NOSPLIT, $0-64
	MOVD	q+0(FP), R0
	MOVD	k+8(FP), R1
	MOVD	panels+16(FP), R2
	MOVD	activation+24(FP), R3
	MOVD	dst+32(FP), R4
	MOVD	n+40(FP), R5
	MOVD	rows+48(FP), R6
	WORD	$0xd503477f	// smstart
	WORD	$0x2598e3e0	// ptrue p0.s
	WORD	$0xd2800011	// mov x17, #0x0 ; =0
	WORD	$0xd37ae428	// lsl x8, x1, #6
	WORD	$0xd37ef4a7	// lsl x7, x5, #2
	WORD	$0xd2800009	// mov x9, #0x0 ; =0
	WORD	$0xc00800ff	// zero {za}
	WORD	$0x25b9ce1f	// fmov z31.s, #1.00000000
	WORD	$0xaa0003ea	// mov x10, x0
	WORD	$0xaa0303eb	// mov x11, x3
	WORD	$0xaa0103ec	// mov x12, x1
	WORD	$0xb40002ac	// cbz x12, 0x80
	WORD	$0xa540a160	// ld1w { z0.s }, p0/z, [x11]
	WORD	$0xa5a0a144	// ld1sb { z4.s }, p0/z, [x10]
	WORD	$0x6594a084	// scvtf z4.s, p0/m, z4.s
	WORD	$0x80840000	// fmopa za0.s, p0/m, p0/m, z0.s, z4.s
	WORD	$0x9100414a	// add x10, x10, #0x10
	WORD	$0xa5a0a144	// ld1sb { z4.s }, p0/z, [x10]
	WORD	$0x6594a084	// scvtf z4.s, p0/m, z4.s
	WORD	$0x80840001	// fmopa za1.s, p0/m, p0/m, z0.s, z4.s
	WORD	$0x9100414a	// add x10, x10, #0x10
	WORD	$0xa5a0a144	// ld1sb { z4.s }, p0/z, [x10]
	WORD	$0x6594a084	// scvtf z4.s, p0/m, z4.s
	WORD	$0x80840002	// fmopa za2.s, p0/m, p0/m, z0.s, z4.s
	WORD	$0x9100414a	// add x10, x10, #0x10
	WORD	$0xa5a0a144	// ld1sb { z4.s }, p0/z, [x10]
	WORD	$0x6594a084	// scvtf z4.s, p0/m, z4.s
	WORD	$0x80840003	// fmopa za3.s, p0/m, p0/m, z0.s, z4.s
	WORD	$0x9100414a	// add x10, x10, #0x10
	WORD	$0x9101016b	// add x11, x11, #0x40
	WORD	$0xd100058c	// sub x12, x12, #0x1
	WORD	$0x17ffffec	// b 0x2c
	WORD	$0x2598e3e3	// ptrue p3.s
	WORD	$0x65922fe4	// fcmeq p4.s, p3/z, z31.s, #0.0
	WORD	$0x2550cc80	// ptest p3, p4.b
	WORD	$0x54000421	// b.ne 0x110
	WORD	$0x25a08c0e	// cntp x14, p3, p0.s
	WORD	$0xf10041df	// cmp x14, #0x10
	WORD	$0x540003c1	// b.ne 0x110
	WORD	$0xd280000d	// mov x13, #0x0 ; =0
	WORD	$0xeb0601bf	// cmp x13, x6
	WORD	$0x5400028a	// b.ge 0xf4
	WORD	$0x9b0711ae	// madd x14, x13, x7, x4
	WORD	$0xcb0918af	// sub x15, x5, x9, lsl #6
	WORD	$0x8b0921ce	// add x14, x14, x9, lsl #8
	WORD	$0x25af17e1	// whilelt p1.s, xzr, x15
	WORD	$0xe0bf25c0	// st1w {za0h.s[w13, 0]}, p1, [x14]
	WORD	$0x910101ce	// add x14, x14, #0x40
	WORD	$0xd10041ef	// sub x15, x15, #0x10
	WORD	$0x25af17e1	// whilelt p1.s, xzr, x15
	WORD	$0xe0bf25c4	// st1w {za1h.s[w13, 0]}, p1, [x14]
	WORD	$0x910101ce	// add x14, x14, #0x40
	WORD	$0xd10041ef	// sub x15, x15, #0x10
	WORD	$0x25af17e1	// whilelt p1.s, xzr, x15
	WORD	$0xe0bf25c8	// st1w {za2h.s[w13, 0]}, p1, [x14]
	WORD	$0x910101ce	// add x14, x14, #0x40
	WORD	$0xd10041ef	// sub x15, x15, #0x10
	WORD	$0x25af17e1	// whilelt p1.s, xzr, x15
	WORD	$0xe0bf25cc	// st1w {za3h.s[w13, 0]}, p1, [x14]
	WORD	$0x910005ad	// add x13, x13, #0x1
	WORD	$0x17ffffec	// b 0xa0
	WORD	$0x8b080000	// add x0, x0, x8
	WORD	$0x91000529	// add x9, x9, #0x1
	WORD	$0xeb02013f	// cmp x9, x2
	WORD	$0x54fff8cb	// b.lt 0x18
	WORD	$0xd503467f	// smstop
	WORD	$0xaa1103e0	// mov x0, x17
	WORD	$0xd65f03c0	// ret
	WORD	$0x91000631	// add x17, x17, #0x1
	WORD	$0x17ffffc1	// b 0x18
	MOVD	R0, retries+56(FP)
	RET

// func smeVectorBytes() int
TEXT ·smeVectorBytes(SB), NOSPLIT, $0-8
	WORD	$0x04bf5820	// rdsvl x0, #1
	MOVD	R0, ret+0(FP)
	RET
