// Code generated by smesrc/build.py; DO NOT EDIT.

//go:build arm64

#include "textflag.h"

// func smeMulF16(q *int8, kPairs, panels int, activation *uint16, dst *float32, cols, rows, strideBytes int, colScales, rowScales *float32) (retries int)
TEXT ·smeMulF16(SB), NOSPLIT, $0-88
	MOVD	q+0(FP), R0
	MOVD	kPairs+8(FP), R1
	MOVD	panels+16(FP), R2
	MOVD	activation+24(FP), R3
	MOVD	dst+32(FP), R4
	MOVD	cols+40(FP), R5
	MOVD	rows+48(FP), R6
	MOVD	strideBytes+56(FP), R7
	MOVD	colScales+64(FP), R16
	MOVD	rowScales+72(FP), R19
	WORD	$0xd503477f	// smstart
	WORD	$0x2598e3e0	// ptrue p0.s
	WORD	$0x2558e3e2	// ptrue p2.h
	WORD	$0xd2800011	// mov x17, #0x0 ; =0
	WORD	$0xd379e028	// lsl x8, x1, #7
	WORD	$0xd2800009	// mov x9, #0x0 ; =0
	WORD	$0xc00800ff	// zero {za}
	WORD	$0x25b9ce1f	// fmov z31.s, #1.00000000
	WORD	$0xaa0003ea	// mov x10, x0
	WORD	$0xaa0303eb	// mov x11, x3
	WORD	$0xaa0103ec	// mov x12, x1
	WORD	$0xb400024c	// cbz x12, 0x74
	WORD	$0xa4a0a960	// ld1h { z0.h }, p2/z, [x11]
	WORD	$0xa5c0a944	// ld1sb { z4.h }, p2/z, [x10]
	WORD	$0xa5c1a945	// ld1sb { z5.h }, p2/z, [x10, #0x1, mul vl]
	WORD	$0xa5c2a946	// ld1sb { z6.h }, p2/z, [x10, #0x2, mul vl]
	WORD	$0xa5c3a947	// ld1sb { z7.h }, p2/z, [x10, #0x3, mul vl]
	WORD	$0x6552a884	// scvtf z4.h, p2/m, z4.h
	WORD	$0x6552a8a5	// scvtf z5.h, p2/m, z5.h
	WORD	$0x6552a8c6	// scvtf z6.h, p2/m, z6.h
	WORD	$0x6552a8e7	// scvtf z7.h, p2/m, z7.h
	WORD	$0x81a44800	// fmopa za0.s, p2/m, p2/m, z0.h, z4.h
	WORD	$0x81a54801	// fmopa za1.s, p2/m, p2/m, z0.h, z5.h
	WORD	$0x81a64802	// fmopa za2.s, p2/m, p2/m, z0.h, z6.h
	WORD	$0x81a74803	// fmopa za3.s, p2/m, p2/m, z0.h, z7.h
	WORD	$0x9102014a	// add x10, x10, #0x80
	WORD	$0x9101016b	// add x11, x11, #0x40
	WORD	$0xd100058c	// sub x12, x12, #0x1
	WORD	$0x17ffffef	// b 0x2c
	WORD	$0x2598e3e3	// ptrue p3.s
	WORD	$0x65922fe4	// fcmeq p4.s, p3/z, z31.s, #0.0
	WORD	$0x2550cc80	// ptest p3, p4.b
	WORD	$0x54000781	// b.ne 0x170
	WORD	$0x25a08c0e	// cntp x14, p3, p0.s
	WORD	$0xf10041df	// cmp x14, #0x10
	WORD	$0x54000721	// b.ne 0x170
	WORD	$0x8b09220f	// add x15, x16, x9, lsl #8
	WORD	$0xcb0918ae	// sub x14, x5, x9, lsl #6
	WORD	$0x25ae17e1	// whilelt p1.s, xzr, x14
	WORD	$0xa540a5f0	// ld1w { z16.s }, p1/z, [x15]
	WORD	$0xd10041ce	// sub x14, x14, #0x10
	WORD	$0x25ae17e1	// whilelt p1.s, xzr, x14
	WORD	$0xa541a5f1	// ld1w { z17.s }, p1/z, [x15, #0x1, mul vl]
	WORD	$0xd10041ce	// sub x14, x14, #0x10
	WORD	$0x25ae17e1	// whilelt p1.s, xzr, x14
	WORD	$0xa542a5f2	// ld1w { z18.s }, p1/z, [x15, #0x2, mul vl]
	WORD	$0xd10041ce	// sub x14, x14, #0x10
	WORD	$0x25ae17e1	// whilelt p1.s, xzr, x14
	WORD	$0xa543a5f3	// ld1w { z19.s }, p1/z, [x15, #0x3, mul vl]
	WORD	$0xd280000d	// mov x13, #0x0 ; =0
	WORD	$0xeb0601bf	// cmp x13, x6
	WORD	$0x540003ea	// b.ge 0x148
	WORD	$0x8b0d0a74	// add x20, x19, x13, lsl #2
	WORD	$0x8540c294	// ld1rw { z20.s }, p0/z, [x20]
	WORD	$0x9b0711ae	// madd x14, x13, x7, x4
	WORD	$0xcb0918af	// sub x15, x5, x9, lsl #6
	WORD	$0x8b0921ce	// add x14, x14, x9, lsl #8
	WORD	$0x25af17e1	// whilelt p1.s, xzr, x15
	WORD	$0xc0822001	// mov z1.s, p0/m, za0h.s[w13, 0]
	WORD	$0x65900821	// fmul z1.s, z1.s, z16.s
	WORD	$0x65940821	// fmul z1.s, z1.s, z20.s
	WORD	$0xe540e5c1	// st1w { z1.s }, p1, [x14]
	WORD	$0xd10041ef	// sub x15, x15, #0x10
	WORD	$0x25af17e1	// whilelt p1.s, xzr, x15
	WORD	$0xc0822082	// mov z2.s, p0/m, za1h.s[w13, 0]
	WORD	$0x65910842	// fmul z2.s, z2.s, z17.s
	WORD	$0x65940842	// fmul z2.s, z2.s, z20.s
	WORD	$0xe541e5c2	// st1w { z2.s }, p1, [x14, #0x1, mul vl]
	WORD	$0xd10041ef	// sub x15, x15, #0x10
	WORD	$0x25af17e1	// whilelt p1.s, xzr, x15
	WORD	$0xc0822103	// mov z3.s, p0/m, za2h.s[w13, 0]
	WORD	$0x65920863	// fmul z3.s, z3.s, z18.s
	WORD	$0x65940863	// fmul z3.s, z3.s, z20.s
	WORD	$0xe542e5c3	// st1w { z3.s }, p1, [x14, #0x2, mul vl]
	WORD	$0xd10041ef	// sub x15, x15, #0x10
	WORD	$0x25af17e1	// whilelt p1.s, xzr, x15
	WORD	$0xc0822181	// mov z1.s, p0/m, za3h.s[w13, 0]
	WORD	$0x65930821	// fmul z1.s, z1.s, z19.s
	WORD	$0x65940821	// fmul z1.s, z1.s, z20.s
	WORD	$0xe543e5c1	// st1w { z1.s }, p1, [x14, #0x3, mul vl]
	WORD	$0x910005ad	// add x13, x13, #0x1
	WORD	$0x17ffffe1	// b 0xc8
	WORD	$0x65922fe4	// fcmeq p4.s, p3/z, z31.s, #0.0
	WORD	$0x2550cc80	// ptest p3, p4.b
	WORD	$0x54000101	// b.ne 0x170
	WORD	$0x8b080000	// add x0, x0, x8
	WORD	$0x91000529	// add x9, x9, #0x1
	WORD	$0xeb02013f	// cmp x9, x2
	WORD	$0x54fff5cb	// b.lt 0x18
	WORD	$0xd503467f	// smstop
	WORD	$0xaa1103e0	// mov x0, x17
	WORD	$0x14000003	// b 0x178
	WORD	$0x91000631	// add x17, x17, #0x1
	WORD	$0x17ffffa9	// b 0x18
	MOVD	R0, retries+80(FP)
	RET

// func smeMulF16W(w *uint16, kPairs, panels int, activation *uint16, dst *float32, cols, rows, strideBytes int, colScales, rowScales *float32) (retries int)
TEXT ·smeMulF16W(SB), NOSPLIT, $0-88
	MOVD	w+0(FP), R0
	MOVD	kPairs+8(FP), R1
	MOVD	panels+16(FP), R2
	MOVD	activation+24(FP), R3
	MOVD	dst+32(FP), R4
	MOVD	cols+40(FP), R5
	MOVD	rows+48(FP), R6
	MOVD	strideBytes+56(FP), R7
	MOVD	colScales+64(FP), R16
	MOVD	rowScales+72(FP), R19
	WORD	$0xd503477f	// smstart
	WORD	$0x2598e3e0	// ptrue p0.s
	WORD	$0x2558e3e2	// ptrue p2.h
	WORD	$0x25607810	// ptrue pn8.h
	WORD	$0xd2800011	// mov x17, #0x0 ; =0
	WORD	$0xd378dc28	// lsl x8, x1, #8
	WORD	$0xd2800009	// mov x9, #0x0 ; =0
	WORD	$0xc00800ff	// zero {za}
	WORD	$0x25b9ce1f	// fmov z31.s, #1.00000000
	WORD	$0xaa0003ea	// mov x10, x0
	WORD	$0xaa0303eb	// mov x11, x3
	WORD	$0xaa0103ec	// mov x12, x1
	WORD	$0xf100119f	// cmp x12, #0x4
	WORD	$0x5400034b	// b.lt 0x9c
	WORD	$0xa040a160	// ld1h { z0.h - z3.h }, pn8/z, [x11]
	WORD	$0xa040a144	// ld1h { z4.h - z7.h }, pn8/z, [x10]
	WORD	$0xa041a148	// ld1h { z8.h - z11.h }, pn8/z, [x10, #0x4, mul vl]
	WORD	$0xa042a14c	// ld1h { z12.h - z15.h }, pn8/z, [x10, #0x8, mul vl]
	WORD	$0xa043a150	// ld1h { z16.h - z19.h }, pn8/z, [x10, #0xc, mul vl]
	WORD	$0x81a44800	// fmopa za0.s, p2/m, p2/m, z0.h, z4.h
	WORD	$0x81a54801	// fmopa za1.s, p2/m, p2/m, z0.h, z5.h
	WORD	$0x81a64802	// fmopa za2.s, p2/m, p2/m, z0.h, z6.h
	WORD	$0x81a74803	// fmopa za3.s, p2/m, p2/m, z0.h, z7.h
	WORD	$0x81a84820	// fmopa za0.s, p2/m, p2/m, z1.h, z8.h
	WORD	$0x81a94821	// fmopa za1.s, p2/m, p2/m, z1.h, z9.h
	WORD	$0x81aa4822	// fmopa za2.s, p2/m, p2/m, z1.h, z10.h
	WORD	$0x81ab4823	// fmopa za3.s, p2/m, p2/m, z1.h, z11.h
	WORD	$0x81ac4840	// fmopa za0.s, p2/m, p2/m, z2.h, z12.h
	WORD	$0x81ad4841	// fmopa za1.s, p2/m, p2/m, z2.h, z13.h
	WORD	$0x81ae4842	// fmopa za2.s, p2/m, p2/m, z2.h, z14.h
	WORD	$0x81af4843	// fmopa za3.s, p2/m, p2/m, z2.h, z15.h
	WORD	$0x81b04860	// fmopa za0.s, p2/m, p2/m, z3.h, z16.h
	WORD	$0x81b14861	// fmopa za1.s, p2/m, p2/m, z3.h, z17.h
	WORD	$0x81b24862	// fmopa za2.s, p2/m, p2/m, z3.h, z18.h
	WORD	$0x81b34863	// fmopa za3.s, p2/m, p2/m, z3.h, z19.h
	WORD	$0x9110014a	// add x10, x10, #0x400
	WORD	$0x9104016b	// add x11, x11, #0x100
	WORD	$0xd100118c	// sub x12, x12, #0x4
	WORD	$0x17ffffe6	// b 0x30
	WORD	$0xb400016c	// cbz x12, 0xc8
	WORD	$0xa4a0a960	// ld1h { z0.h }, p2/z, [x11]
	WORD	$0xa040a144	// ld1h { z4.h - z7.h }, pn8/z, [x10]
	WORD	$0x81a44800	// fmopa za0.s, p2/m, p2/m, z0.h, z4.h
	WORD	$0x81a54801	// fmopa za1.s, p2/m, p2/m, z0.h, z5.h
	WORD	$0x81a64802	// fmopa za2.s, p2/m, p2/m, z0.h, z6.h
	WORD	$0x81a74803	// fmopa za3.s, p2/m, p2/m, z0.h, z7.h
	WORD	$0x9104014a	// add x10, x10, #0x100
	WORD	$0x9101016b	// add x11, x11, #0x40
	WORD	$0xd100058c	// sub x12, x12, #0x1
	WORD	$0x17fffff6	// b 0x9c
	WORD	$0x2598e3e3	// ptrue p3.s
	WORD	$0x65922fe4	// fcmeq p4.s, p3/z, z31.s, #0.0
	WORD	$0x2550cc80	// ptest p3, p4.b
	WORD	$0x54000781	// b.ne 0x1c4
	WORD	$0x25a08c0e	// cntp x14, p3, p0.s
	WORD	$0xf10041df	// cmp x14, #0x10
	WORD	$0x54000721	// b.ne 0x1c4
	WORD	$0x8b09220f	// add x15, x16, x9, lsl #8
	WORD	$0xcb0918ae	// sub x14, x5, x9, lsl #6
	WORD	$0x25ae17e1	// whilelt p1.s, xzr, x14
	WORD	$0xa540a5f0	// ld1w { z16.s }, p1/z, [x15]
	WORD	$0xd10041ce	// sub x14, x14, #0x10
	WORD	$0x25ae17e1	// whilelt p1.s, xzr, x14
	WORD	$0xa541a5f1	// ld1w { z17.s }, p1/z, [x15, #0x1, mul vl]
	WORD	$0xd10041ce	// sub x14, x14, #0x10
	WORD	$0x25ae17e1	// whilelt p1.s, xzr, x14
	WORD	$0xa542a5f2	// ld1w { z18.s }, p1/z, [x15, #0x2, mul vl]
	WORD	$0xd10041ce	// sub x14, x14, #0x10
	WORD	$0x25ae17e1	// whilelt p1.s, xzr, x14
	WORD	$0xa543a5f3	// ld1w { z19.s }, p1/z, [x15, #0x3, mul vl]
	WORD	$0xd280000d	// mov x13, #0x0 ; =0
	WORD	$0xeb0601bf	// cmp x13, x6
	WORD	$0x540003ea	// b.ge 0x19c
	WORD	$0x8b0d0a74	// add x20, x19, x13, lsl #2
	WORD	$0x8540c294	// ld1rw { z20.s }, p0/z, [x20]
	WORD	$0x9b0711ae	// madd x14, x13, x7, x4
	WORD	$0xcb0918af	// sub x15, x5, x9, lsl #6
	WORD	$0x8b0921ce	// add x14, x14, x9, lsl #8
	WORD	$0x25af17e1	// whilelt p1.s, xzr, x15
	WORD	$0xc0822001	// mov z1.s, p0/m, za0h.s[w13, 0]
	WORD	$0x65900821	// fmul z1.s, z1.s, z16.s
	WORD	$0x65940821	// fmul z1.s, z1.s, z20.s
	WORD	$0xe540e5c1	// st1w { z1.s }, p1, [x14]
	WORD	$0xd10041ef	// sub x15, x15, #0x10
	WORD	$0x25af17e1	// whilelt p1.s, xzr, x15
	WORD	$0xc0822082	// mov z2.s, p0/m, za1h.s[w13, 0]
	WORD	$0x65910842	// fmul z2.s, z2.s, z17.s
	WORD	$0x65940842	// fmul z2.s, z2.s, z20.s
	WORD	$0xe541e5c2	// st1w { z2.s }, p1, [x14, #0x1, mul vl]
	WORD	$0xd10041ef	// sub x15, x15, #0x10
	WORD	$0x25af17e1	// whilelt p1.s, xzr, x15
	WORD	$0xc0822103	// mov z3.s, p0/m, za2h.s[w13, 0]
	WORD	$0x65920863	// fmul z3.s, z3.s, z18.s
	WORD	$0x65940863	// fmul z3.s, z3.s, z20.s
	WORD	$0xe542e5c3	// st1w { z3.s }, p1, [x14, #0x2, mul vl]
	WORD	$0xd10041ef	// sub x15, x15, #0x10
	WORD	$0x25af17e1	// whilelt p1.s, xzr, x15
	WORD	$0xc0822181	// mov z1.s, p0/m, za3h.s[w13, 0]
	WORD	$0x65930821	// fmul z1.s, z1.s, z19.s
	WORD	$0x65940821	// fmul z1.s, z1.s, z20.s
	WORD	$0xe543e5c1	// st1w { z1.s }, p1, [x14, #0x3, mul vl]
	WORD	$0x910005ad	// add x13, x13, #0x1
	WORD	$0x17ffffe1	// b 0x11c
	WORD	$0x65922fe4	// fcmeq p4.s, p3/z, z31.s, #0.0
	WORD	$0x2550cc80	// ptest p3, p4.b
	WORD	$0x54000101	// b.ne 0x1c4
	WORD	$0x8b080000	// add x0, x0, x8
	WORD	$0x91000529	// add x9, x9, #0x1
	WORD	$0xeb02013f	// cmp x9, x2
	WORD	$0x54fff34b	// b.lt 0x1c
	WORD	$0xd503467f	// smstop
	WORD	$0xaa1103e0	// mov x0, x17
	WORD	$0x14000003	// b 0x1cc
	WORD	$0x91000631	// add x17, x17, #0x1
	WORD	$0x17ffff95	// b 0x1c
	MOVD	R0, retries+80(FP)
	RET

// func smeMulI8(w *int8, kQuads, panels int, activation *int8, dst *float32, cols, rows, strideBytes int, colScales, rowScales *float32) (retries int)
TEXT ·smeMulI8(SB), NOSPLIT, $0-88
	MOVD	w+0(FP), R0
	MOVD	kQuads+8(FP), R1
	MOVD	panels+16(FP), R2
	MOVD	activation+24(FP), R3
	MOVD	dst+32(FP), R4
	MOVD	cols+40(FP), R5
	MOVD	rows+48(FP), R6
	MOVD	strideBytes+56(FP), R7
	MOVD	colScales+64(FP), R16
	MOVD	rowScales+72(FP), R19
	WORD	$0xd503477f	// smstart
	WORD	$0x2598e3e0	// ptrue p0.s
	WORD	$0x2518e3e2	// ptrue p2.b
	WORD	$0xd2800011	// mov x17, #0x0 ; =0
	WORD	$0xd378dc28	// lsl x8, x1, #8
	WORD	$0xd2800009	// mov x9, #0x0 ; =0
	WORD	$0xc00800ff	// zero {za}
	WORD	$0x25b9ce1f	// fmov z31.s, #1.00000000
	WORD	$0xaa0003ea	// mov x10, x0
	WORD	$0xaa0303eb	// mov x11, x3
	WORD	$0xaa0103ec	// mov x12, x1
	WORD	$0xb40001cc	// cbz x12, 0x64
	WORD	$0xa400a960	// ld1b { z0.b }, p2/z, [x11]
	WORD	$0xa400a944	// ld1b { z4.b }, p2/z, [x10]
	WORD	$0xa401a945	// ld1b { z5.b }, p2/z, [x10, #0x1, mul vl]
	WORD	$0xa402a946	// ld1b { z6.b }, p2/z, [x10, #0x2, mul vl]
	WORD	$0xa403a947	// ld1b { z7.b }, p2/z, [x10, #0x3, mul vl]
	WORD	$0xa0844800	// smopa za0.s, p2/m, p2/m, z0.b, z4.b
	WORD	$0xa0854801	// smopa za1.s, p2/m, p2/m, z0.b, z5.b
	WORD	$0xa0864802	// smopa za2.s, p2/m, p2/m, z0.b, z6.b
	WORD	$0xa0874803	// smopa za3.s, p2/m, p2/m, z0.b, z7.b
	WORD	$0x9104014a	// add x10, x10, #0x100
	WORD	$0x9101016b	// add x11, x11, #0x40
	WORD	$0xd100058c	// sub x12, x12, #0x1
	WORD	$0x17fffff3	// b 0x2c
	WORD	$0x2598e3e3	// ptrue p3.s
	WORD	$0x65922fe4	// fcmeq p4.s, p3/z, z31.s, #0.0
	WORD	$0x2550cc80	// ptest p3, p4.b
	WORD	$0x54000801	// b.ne 0x170
	WORD	$0x25a08c0e	// cntp x14, p3, p0.s
	WORD	$0xf10041df	// cmp x14, #0x10
	WORD	$0x540007a1	// b.ne 0x170
	WORD	$0x8b09220f	// add x15, x16, x9, lsl #8
	WORD	$0xcb0918ae	// sub x14, x5, x9, lsl #6
	WORD	$0x25ae17e1	// whilelt p1.s, xzr, x14
	WORD	$0xa540a5f0	// ld1w { z16.s }, p1/z, [x15]
	WORD	$0xd10041ce	// sub x14, x14, #0x10
	WORD	$0x25ae17e1	// whilelt p1.s, xzr, x14
	WORD	$0xa541a5f1	// ld1w { z17.s }, p1/z, [x15, #0x1, mul vl]
	WORD	$0xd10041ce	// sub x14, x14, #0x10
	WORD	$0x25ae17e1	// whilelt p1.s, xzr, x14
	WORD	$0xa542a5f2	// ld1w { z18.s }, p1/z, [x15, #0x2, mul vl]
	WORD	$0xd10041ce	// sub x14, x14, #0x10
	WORD	$0x25ae17e1	// whilelt p1.s, xzr, x14
	WORD	$0xa543a5f3	// ld1w { z19.s }, p1/z, [x15, #0x3, mul vl]
	WORD	$0xd280000d	// mov x13, #0x0 ; =0
	WORD	$0xeb0601bf	// cmp x13, x6
	WORD	$0x5400046a	// b.ge 0x148
	WORD	$0x8b0d0a74	// add x20, x19, x13, lsl #2
	WORD	$0x8540c294	// ld1rw { z20.s }, p0/z, [x20]
	WORD	$0x9b0711ae	// madd x14, x13, x7, x4
	WORD	$0xcb0918af	// sub x15, x5, x9, lsl #6
	WORD	$0x8b0921ce	// add x14, x14, x9, lsl #8
	WORD	$0x25af17e1	// whilelt p1.s, xzr, x15
	WORD	$0xc0822001	// mov z1.s, p0/m, za0h.s[w13, 0]
	WORD	$0x6594a021	// scvtf z1.s, p0/m, z1.s
	WORD	$0x65900821	// fmul z1.s, z1.s, z16.s
	WORD	$0x65940821	// fmul z1.s, z1.s, z20.s
	WORD	$0xe540e5c1	// st1w { z1.s }, p1, [x14]
	WORD	$0xd10041ef	// sub x15, x15, #0x10
	WORD	$0x25af17e1	// whilelt p1.s, xzr, x15
	WORD	$0xc0822082	// mov z2.s, p0/m, za1h.s[w13, 0]
	WORD	$0x6594a042	// scvtf z2.s, p0/m, z2.s
	WORD	$0x65910842	// fmul z2.s, z2.s, z17.s
	WORD	$0x65940842	// fmul z2.s, z2.s, z20.s
	WORD	$0xe541e5c2	// st1w { z2.s }, p1, [x14, #0x1, mul vl]
	WORD	$0xd10041ef	// sub x15, x15, #0x10
	WORD	$0x25af17e1	// whilelt p1.s, xzr, x15
	WORD	$0xc0822103	// mov z3.s, p0/m, za2h.s[w13, 0]
	WORD	$0x6594a063	// scvtf z3.s, p0/m, z3.s
	WORD	$0x65920863	// fmul z3.s, z3.s, z18.s
	WORD	$0x65940863	// fmul z3.s, z3.s, z20.s
	WORD	$0xe542e5c3	// st1w { z3.s }, p1, [x14, #0x2, mul vl]
	WORD	$0xd10041ef	// sub x15, x15, #0x10
	WORD	$0x25af17e1	// whilelt p1.s, xzr, x15
	WORD	$0xc0822181	// mov z1.s, p0/m, za3h.s[w13, 0]
	WORD	$0x6594a021	// scvtf z1.s, p0/m, z1.s
	WORD	$0x65930821	// fmul z1.s, z1.s, z19.s
	WORD	$0x65940821	// fmul z1.s, z1.s, z20.s
	WORD	$0xe543e5c1	// st1w { z1.s }, p1, [x14, #0x3, mul vl]
	WORD	$0x910005ad	// add x13, x13, #0x1
	WORD	$0x17ffffdd	// b 0xb8
	WORD	$0x65922fe4	// fcmeq p4.s, p3/z, z31.s, #0.0
	WORD	$0x2550cc80	// ptest p3, p4.b
	WORD	$0x54000101	// b.ne 0x170
	WORD	$0x8b080000	// add x0, x0, x8
	WORD	$0x91000529	// add x9, x9, #0x1
	WORD	$0xeb02013f	// cmp x9, x2
	WORD	$0x54fff5cb	// b.lt 0x18
	WORD	$0xd503467f	// smstop
	WORD	$0xaa1103e0	// mov x0, x17
	WORD	$0x14000003	// b 0x178
	WORD	$0x91000631	// add x17, x17, #0x1
	WORD	$0x17ffffa9	// b 0x18
	MOVD	R0, retries+80(FP)
	RET

// func smeRowI8(w *int8, kGroups, panels int, activation *int8, dst *float32, cols int, colScales, rowScale *float32) (retries int)
TEXT ·smeRowI8(SB), NOSPLIT, $0-72
	MOVD	w+0(FP), R0
	MOVD	kGroups+8(FP), R1
	MOVD	panels+16(FP), R2
	MOVD	activation+24(FP), R3
	MOVD	dst+32(FP), R4
	MOVD	cols+40(FP), R5
	MOVD	colScales+48(FP), R16
	MOVD	rowScale+56(FP), R19
	WORD	$0xd503477f	// smstart
	WORD	$0xd2800011	// mov x17, #0x0 ; =0
	WORD	$0xd375d027	// lsl x7, x1, #11
	WORD	$0xd2800009	// mov x9, #0x0 ; =0
	WORD	$0x52800008	// mov w8, #0x0 ; =0
	WORD	$0xc00800ff	// zero {za}
	WORD	$0x25b9ce1f	// fmov z31.s, #1.00000000
	WORD	$0x2518e3e0	// ptrue p0.b
	WORD	$0x2598e3e1	// ptrue p1.s
	WORD	$0x25207810	// ptrue pn8.b
	WORD	$0x8540c674	// ld1rw { z20.s }, p1/z, [x19]
	WORD	$0xaa0003ea	// mov x10, x0
	WORD	$0xaa0303eb	// mov x11, x3
	WORD	$0xaa0103ec	// mov x12, x1
	WORD	$0xb400030c	// cbz x12, 0x98
	WORD	$0xa4002160	// ld1rqb { z0.b }, p0/z, [x11]
	WORD	$0xa4012161	// ld1rqb { z1.b }, p0/z, [x11, #0x10]
	WORD	$0xa0408144	// ld1b { z4.b - z7.b }, pn8/z, [x10]
	WORD	$0xc15090a0	// sdot za.s[w8, 0, vgx4], { z4.b - z7.b }, z0.b[0]
	WORD	$0xa0418148	// ld1b { z8.b - z11.b }, pn8/z, [x10, #0x4, mul vl]
	WORD	$0xc1509521	// sdot za.s[w8, 1, vgx4], { z8.b - z11.b }, z0.b[1]
	WORD	$0xa042814c	// ld1b { z12.b - z15.b }, pn8/z, [x10, #0x8, mul vl]
	WORD	$0xc15099a2	// sdot za.s[w8, 2, vgx4], { z12.b - z15.b }, z0.b[2]
	WORD	$0xa0438150	// ld1b { z16.b - z19.b }, pn8/z, [x10, #0xc, mul vl]
	WORD	$0xc1509e23	// sdot za.s[w8, 3, vgx4], { z16.b - z19.b }, z0.b[3]
	WORD	$0x9110014a	// add x10, x10, #0x400
	WORD	$0xa0408144	// ld1b { z4.b - z7.b }, pn8/z, [x10]
	WORD	$0xc15190a4	// sdot za.s[w8, 4, vgx4], { z4.b - z7.b }, z1.b[0]
	WORD	$0xa0418148	// ld1b { z8.b - z11.b }, pn8/z, [x10, #0x4, mul vl]
	WORD	$0xc1519525	// sdot za.s[w8, 5, vgx4], { z8.b - z11.b }, z1.b[1]
	WORD	$0xa042814c	// ld1b { z12.b - z15.b }, pn8/z, [x10, #0x8, mul vl]
	WORD	$0xc15199a6	// sdot za.s[w8, 6, vgx4], { z12.b - z15.b }, z1.b[2]
	WORD	$0xa0438150	// ld1b { z16.b - z19.b }, pn8/z, [x10, #0xc, mul vl]
	WORD	$0xc1519e27	// sdot za.s[w8, 7, vgx4], { z16.b - z19.b }, z1.b[3]
	WORD	$0x9110014a	// add x10, x10, #0x400
	WORD	$0x9100816b	// add x11, x11, #0x20
	WORD	$0xd100058c	// sub x12, x12, #0x1
	WORD	$0x17ffffe9	// b 0x38
	WORD	$0x052603ff	// ext z31.b, z31.b, z31.b, #0x30
	WORD	$0x1e2603ee	// fmov w14, s31
	WORD	$0x340009ae	// cbz w14, 0x1d4
	WORD	$0xc0060c00	// mov { z0.d - z3.d }, za.d[w8, 0, vgx4]
	WORD	$0xc0060c24	// mov { z4.d - z7.d }, za.d[w8, 1, vgx4]
	WORD	$0x04a40000	// add z0.s, z0.s, z4.s
	WORD	$0x04a50021	// add z1.s, z1.s, z5.s
	WORD	$0x04a60042	// add z2.s, z2.s, z6.s
	WORD	$0x04a70063	// add z3.s, z3.s, z7.s
	WORD	$0xc0060c44	// mov { z4.d - z7.d }, za.d[w8, 2, vgx4]
	WORD	$0x04a40000	// add z0.s, z0.s, z4.s
	WORD	$0x04a50021	// add z1.s, z1.s, z5.s
	WORD	$0x04a60042	// add z2.s, z2.s, z6.s
	WORD	$0x04a70063	// add z3.s, z3.s, z7.s
	WORD	$0xc0060c64	// mov { z4.d - z7.d }, za.d[w8, 3, vgx4]
	WORD	$0x04a40000	// add z0.s, z0.s, z4.s
	WORD	$0x04a50021	// add z1.s, z1.s, z5.s
	WORD	$0x04a60042	// add z2.s, z2.s, z6.s
	WORD	$0x04a70063	// add z3.s, z3.s, z7.s
	WORD	$0xc0060c84	// mov { z4.d - z7.d }, za.d[w8, 4, vgx4]
	WORD	$0x04a40000	// add z0.s, z0.s, z4.s
	WORD	$0x04a50021	// add z1.s, z1.s, z5.s
	WORD	$0x04a60042	// add z2.s, z2.s, z6.s
	WORD	$0x04a70063	// add z3.s, z3.s, z7.s
	WORD	$0xc0060ca4	// mov { z4.d - z7.d }, za.d[w8, 5, vgx4]
	WORD	$0x04a40000	// add z0.s, z0.s, z4.s
	WORD	$0x04a50021	// add z1.s, z1.s, z5.s
	WORD	$0x04a60042	// add z2.s, z2.s, z6.s
	WORD	$0x04a70063	// add z3.s, z3.s, z7.s
	WORD	$0xc0060cc4	// mov { z4.d - z7.d }, za.d[w8, 6, vgx4]
	WORD	$0x04a40000	// add z0.s, z0.s, z4.s
	WORD	$0x04a50021	// add z1.s, z1.s, z5.s
	WORD	$0x04a60042	// add z2.s, z2.s, z6.s
	WORD	$0x04a70063	// add z3.s, z3.s, z7.s
	WORD	$0xc0060ce4	// mov { z4.d - z7.d }, za.d[w8, 7, vgx4]
	WORD	$0x04a40000	// add z0.s, z0.s, z4.s
	WORD	$0x04a50021	// add z1.s, z1.s, z5.s
	WORD	$0x04a60042	// add z2.s, z2.s, z6.s
	WORD	$0x04a70063	// add z3.s, z3.s, z7.s
	WORD	$0x6594a400	// scvtf z0.s, p1/m, z0.s
	WORD	$0x6594a421	// scvtf z1.s, p1/m, z1.s
	WORD	$0x6594a442	// scvtf z2.s, p1/m, z2.s
	WORD	$0x6594a463	// scvtf z3.s, p1/m, z3.s
	WORD	$0x8b09220f	// add x15, x16, x9, lsl #8
	WORD	$0x8b09208e	// add x14, x4, x9, lsl #8
	WORD	$0xcb0918ad	// sub x13, x5, x9, lsl #6
	WORD	$0x25ad17e2	// whilelt p2.s, xzr, x13
	WORD	$0xa540a9e8	// ld1w { z8.s }, p2/z, [x15]
	WORD	$0x65880800	// fmul z0.s, z0.s, z8.s
	WORD	$0x65940800	// fmul z0.s, z0.s, z20.s
	WORD	$0xe540e9c0	// st1w { z0.s }, p2, [x14]
	WORD	$0xd10041ad	// sub x13, x13, #0x10
	WORD	$0x25ad17e2	// whilelt p2.s, xzr, x13
	WORD	$0xa541a9e8	// ld1w { z8.s }, p2/z, [x15, #0x1, mul vl]
	WORD	$0x65880821	// fmul z1.s, z1.s, z8.s
	WORD	$0x65940821	// fmul z1.s, z1.s, z20.s
	WORD	$0xe541e9c1	// st1w { z1.s }, p2, [x14, #0x1, mul vl]
	WORD	$0xd10041ad	// sub x13, x13, #0x10
	WORD	$0x25ad17e2	// whilelt p2.s, xzr, x13
	WORD	$0xa542a9e8	// ld1w { z8.s }, p2/z, [x15, #0x2, mul vl]
	WORD	$0x65880842	// fmul z2.s, z2.s, z8.s
	WORD	$0x65940842	// fmul z2.s, z2.s, z20.s
	WORD	$0xe542e9c2	// st1w { z2.s }, p2, [x14, #0x2, mul vl]
	WORD	$0xd10041ad	// sub x13, x13, #0x10
	WORD	$0x25ad17e2	// whilelt p2.s, xzr, x13
	WORD	$0xa543a9e8	// ld1w { z8.s }, p2/z, [x15, #0x3, mul vl]
	WORD	$0x65880863	// fmul z3.s, z3.s, z8.s
	WORD	$0x65940863	// fmul z3.s, z3.s, z20.s
	WORD	$0xe543e9c3	// st1w { z3.s }, p2, [x14, #0x3, mul vl]
	WORD	$0x052603ff	// ext z31.b, z31.b, z31.b, #0x30
	WORD	$0x1e2603ee	// fmov w14, s31
	WORD	$0x3400010e	// cbz w14, 0x1d4
	WORD	$0x8b070000	// add x0, x0, x7
	WORD	$0x91000529	// add x9, x9, #0x1
	WORD	$0xeb02013f	// cmp x9, x2
	WORD	$0x54fff28b	// b.lt 0x14
	WORD	$0xd503467f	// smstop
	WORD	$0xaa1103e0	// mov x0, x17
	WORD	$0x14000003	// b 0x1dc
	WORD	$0x91000631	// add x17, x17, #0x1
	WORD	$0x17ffff8f	// b 0x14
	MOVD	R0, retries+64(FP)
	RET

// func smeRowF16(w *uint16, kGroups, panels int, activation *uint16, dst *float32, cols int, colScales, rowScale *float32) (retries int)
TEXT ·smeRowF16(SB), NOSPLIT, $0-72
	MOVD	w+0(FP), R0
	MOVD	kGroups+8(FP), R1
	MOVD	panels+16(FP), R2
	MOVD	activation+24(FP), R3
	MOVD	dst+32(FP), R4
	MOVD	cols+40(FP), R5
	MOVD	colScales+48(FP), R16
	MOVD	rowScale+56(FP), R19
	WORD	$0xd503477f	// smstart
	WORD	$0xd2800011	// mov x17, #0x0 ; =0
	WORD	$0xd375d027	// lsl x7, x1, #11
	WORD	$0xd2800009	// mov x9, #0x0 ; =0
	WORD	$0x52800008	// mov w8, #0x0 ; =0
	WORD	$0xc00800ff	// zero {za}
	WORD	$0x25b9ce1f	// fmov z31.s, #1.00000000
	WORD	$0x2558e3e0	// ptrue p0.h
	WORD	$0x2598e3e1	// ptrue p1.s
	WORD	$0x25607810	// ptrue pn8.h
	WORD	$0x8540c674	// ld1rw { z20.s }, p1/z, [x19]
	WORD	$0xaa0003ea	// mov x10, x0
	WORD	$0xaa0303eb	// mov x11, x3
	WORD	$0xaa0103ec	// mov x12, x1
	WORD	$0xb400030c	// cbz x12, 0x98
	WORD	$0xa4802160	// ld1rqh { z0.h }, p0/z, [x11]
	WORD	$0xa4812161	// ld1rqh { z1.h }, p0/z, [x11, #0x10]
	WORD	$0xa040a144	// ld1h { z4.h - z7.h }, pn8/z, [x10]
	WORD	$0xc1509088	// fdot za.s[w8, 0, vgx4], { z4.h - z7.h }, z0.h[0]
	WORD	$0xa041a148	// ld1h { z8.h - z11.h }, pn8/z, [x10, #0x4, mul vl]
	WORD	$0xc1509509	// fdot za.s[w8, 1, vgx4], { z8.h - z11.h }, z0.h[1]
	WORD	$0xa042a14c	// ld1h { z12.h - z15.h }, pn8/z, [x10, #0x8, mul vl]
	WORD	$0xc150998a	// fdot za.s[w8, 2, vgx4], { z12.h - z15.h }, z0.h[2]
	WORD	$0xa043a150	// ld1h { z16.h - z19.h }, pn8/z, [x10, #0xc, mul vl]
	WORD	$0xc1509e0b	// fdot za.s[w8, 3, vgx4], { z16.h - z19.h }, z0.h[3]
	WORD	$0x9110014a	// add x10, x10, #0x400
	WORD	$0xa040a144	// ld1h { z4.h - z7.h }, pn8/z, [x10]
	WORD	$0xc151908c	// fdot za.s[w8, 4, vgx4], { z4.h - z7.h }, z1.h[0]
	WORD	$0xa041a148	// ld1h { z8.h - z11.h }, pn8/z, [x10, #0x4, mul vl]
	WORD	$0xc151950d	// fdot za.s[w8, 5, vgx4], { z8.h - z11.h }, z1.h[1]
	WORD	$0xa042a14c	// ld1h { z12.h - z15.h }, pn8/z, [x10, #0x8, mul vl]
	WORD	$0xc151998e	// fdot za.s[w8, 6, vgx4], { z12.h - z15.h }, z1.h[2]
	WORD	$0xa043a150	// ld1h { z16.h - z19.h }, pn8/z, [x10, #0xc, mul vl]
	WORD	$0xc1519e0f	// fdot za.s[w8, 7, vgx4], { z16.h - z19.h }, z1.h[3]
	WORD	$0x9110014a	// add x10, x10, #0x400
	WORD	$0x9100816b	// add x11, x11, #0x20
	WORD	$0xd100058c	// sub x12, x12, #0x1
	WORD	$0x17ffffe9	// b 0x38
	WORD	$0x052603ff	// ext z31.b, z31.b, z31.b, #0x30
	WORD	$0x1e2603ee	// fmov w14, s31
	WORD	$0x3400092e	// cbz w14, 0x1c4
	WORD	$0xc0060c00	// mov { z0.d - z3.d }, za.d[w8, 0, vgx4]
	WORD	$0xc0060c24	// mov { z4.d - z7.d }, za.d[w8, 1, vgx4]
	WORD	$0x65840000	// fadd z0.s, z0.s, z4.s
	WORD	$0x65850021	// fadd z1.s, z1.s, z5.s
	WORD	$0x65860042	// fadd z2.s, z2.s, z6.s
	WORD	$0x65870063	// fadd z3.s, z3.s, z7.s
	WORD	$0xc0060c44	// mov { z4.d - z7.d }, za.d[w8, 2, vgx4]
	WORD	$0x65840000	// fadd z0.s, z0.s, z4.s
	WORD	$0x65850021	// fadd z1.s, z1.s, z5.s
	WORD	$0x65860042	// fadd z2.s, z2.s, z6.s
	WORD	$0x65870063	// fadd z3.s, z3.s, z7.s
	WORD	$0xc0060c64	// mov { z4.d - z7.d }, za.d[w8, 3, vgx4]
	WORD	$0x65840000	// fadd z0.s, z0.s, z4.s
	WORD	$0x65850021	// fadd z1.s, z1.s, z5.s
	WORD	$0x65860042	// fadd z2.s, z2.s, z6.s
	WORD	$0x65870063	// fadd z3.s, z3.s, z7.s
	WORD	$0xc0060c84	// mov { z4.d - z7.d }, za.d[w8, 4, vgx4]
	WORD	$0x65840000	// fadd z0.s, z0.s, z4.s
	WORD	$0x65850021	// fadd z1.s, z1.s, z5.s
	WORD	$0x65860042	// fadd z2.s, z2.s, z6.s
	WORD	$0x65870063	// fadd z3.s, z3.s, z7.s
	WORD	$0xc0060ca4	// mov { z4.d - z7.d }, za.d[w8, 5, vgx4]
	WORD	$0x65840000	// fadd z0.s, z0.s, z4.s
	WORD	$0x65850021	// fadd z1.s, z1.s, z5.s
	WORD	$0x65860042	// fadd z2.s, z2.s, z6.s
	WORD	$0x65870063	// fadd z3.s, z3.s, z7.s
	WORD	$0xc0060cc4	// mov { z4.d - z7.d }, za.d[w8, 6, vgx4]
	WORD	$0x65840000	// fadd z0.s, z0.s, z4.s
	WORD	$0x65850021	// fadd z1.s, z1.s, z5.s
	WORD	$0x65860042	// fadd z2.s, z2.s, z6.s
	WORD	$0x65870063	// fadd z3.s, z3.s, z7.s
	WORD	$0xc0060ce4	// mov { z4.d - z7.d }, za.d[w8, 7, vgx4]
	WORD	$0x65840000	// fadd z0.s, z0.s, z4.s
	WORD	$0x65850021	// fadd z1.s, z1.s, z5.s
	WORD	$0x65860042	// fadd z2.s, z2.s, z6.s
	WORD	$0x65870063	// fadd z3.s, z3.s, z7.s
	WORD	$0x8b09220f	// add x15, x16, x9, lsl #8
	WORD	$0x8b09208e	// add x14, x4, x9, lsl #8
	WORD	$0xcb0918ad	// sub x13, x5, x9, lsl #6
	WORD	$0x25ad17e2	// whilelt p2.s, xzr, x13
	WORD	$0xa540a9e8	// ld1w { z8.s }, p2/z, [x15]
	WORD	$0x65880800	// fmul z0.s, z0.s, z8.s
	WORD	$0x65940800	// fmul z0.s, z0.s, z20.s
	WORD	$0xe540e9c0	// st1w { z0.s }, p2, [x14]
	WORD	$0xd10041ad	// sub x13, x13, #0x10
	WORD	$0x25ad17e2	// whilelt p2.s, xzr, x13
	WORD	$0xa541a9e8	// ld1w { z8.s }, p2/z, [x15, #0x1, mul vl]
	WORD	$0x65880821	// fmul z1.s, z1.s, z8.s
	WORD	$0x65940821	// fmul z1.s, z1.s, z20.s
	WORD	$0xe541e9c1	// st1w { z1.s }, p2, [x14, #0x1, mul vl]
	WORD	$0xd10041ad	// sub x13, x13, #0x10
	WORD	$0x25ad17e2	// whilelt p2.s, xzr, x13
	WORD	$0xa542a9e8	// ld1w { z8.s }, p2/z, [x15, #0x2, mul vl]
	WORD	$0x65880842	// fmul z2.s, z2.s, z8.s
	WORD	$0x65940842	// fmul z2.s, z2.s, z20.s
	WORD	$0xe542e9c2	// st1w { z2.s }, p2, [x14, #0x2, mul vl]
	WORD	$0xd10041ad	// sub x13, x13, #0x10
	WORD	$0x25ad17e2	// whilelt p2.s, xzr, x13
	WORD	$0xa543a9e8	// ld1w { z8.s }, p2/z, [x15, #0x3, mul vl]
	WORD	$0x65880863	// fmul z3.s, z3.s, z8.s
	WORD	$0x65940863	// fmul z3.s, z3.s, z20.s
	WORD	$0xe543e9c3	// st1w { z3.s }, p2, [x14, #0x3, mul vl]
	WORD	$0x052603ff	// ext z31.b, z31.b, z31.b, #0x30
	WORD	$0x1e2603ee	// fmov w14, s31
	WORD	$0x3400010e	// cbz w14, 0x1c4
	WORD	$0x8b070000	// add x0, x0, x7
	WORD	$0x91000529	// add x9, x9, #0x1
	WORD	$0xeb02013f	// cmp x9, x2
	WORD	$0x54fff30b	// b.lt 0x14
	WORD	$0xd503467f	// smstop
	WORD	$0xaa1103e0	// mov x0, x17
	WORD	$0x14000003	// b 0x1cc
	WORD	$0x91000631	// add x17, x17, #0x1
	WORD	$0x17ffff93	// b 0x14
	MOVD	R0, retries+64(FP)
	RET

// func smeRows2F16(w *uint16, kGroups, panels int, activation *uint16, dst *float32, cols, strideBytes int, colScales, rowScales *float32) (retries int)
TEXT ·smeRows2F16(SB), NOSPLIT, $0-80
	MOVD	w+0(FP), R0
	MOVD	kGroups+8(FP), R1
	MOVD	panels+16(FP), R2
	MOVD	activation+24(FP), R3
	MOVD	dst+32(FP), R4
	MOVD	cols+40(FP), R5
	MOVD	strideBytes+48(FP), R6
	MOVD	colScales+56(FP), R16
	MOVD	rowScales+64(FP), R19
	WORD	$0xd503477f	// smstart
	WORD	$0xd2800011	// mov x17, #0x0 ; =0
	WORD	$0xd375d027	// lsl x7, x1, #11
	WORD	$0xd2800014	// mov x20, #0x0 ; =0
	WORD	$0x52800008	// mov w8, #0x0 ; =0
	WORD	$0x52800109	// mov w9, #0x8 ; =8
	WORD	$0xd37be836	// lsl x22, x1, #5
	WORD	$0xc00800ff	// zero {za}
	WORD	$0x25b9ce1f	// fmov z31.s, #1.00000000
	WORD	$0x2558e3e0	// ptrue p0.h
	WORD	$0x2598e3e1	// ptrue p1.s
	WORD	$0x25607810	// ptrue pn8.h
	WORD	$0x8540c674	// ld1rw { z20.s }, p1/z, [x19]
	WORD	$0x8541c675	// ld1rw { z21.s }, p1/z, [x19, #0x4]
	WORD	$0xaa0003ea	// mov x10, x0
	WORD	$0xaa0303eb	// mov x11, x3
	WORD	$0x8b160075	// add x21, x3, x22
	WORD	$0xaa0103ec	// mov x12, x1
	WORD	$0xb400046c	// cbz x12, 0xd4
	WORD	$0xa4802160	// ld1rqh { z0.h }, p0/z, [x11]
	WORD	$0xa4812161	// ld1rqh { z1.h }, p0/z, [x11, #0x10]
	WORD	$0xa48022a2	// ld1rqh { z2.h }, p0/z, [x21]
	WORD	$0xa48122a3	// ld1rqh { z3.h }, p0/z, [x21, #0x10]
	WORD	$0xa040a144	// ld1h { z4.h - z7.h }, pn8/z, [x10]
	WORD	$0xc1509088	// fdot za.s[w8, 0, vgx4], { z4.h - z7.h }, z0.h[0]
	WORD	$0xc152b088	// fdot za.s[w9, 0, vgx4], { z4.h - z7.h }, z2.h[0]
	WORD	$0xa041a148	// ld1h { z8.h - z11.h }, pn8/z, [x10, #0x4, mul vl]
	WORD	$0xc1509509	// fdot za.s[w8, 1, vgx4], { z8.h - z11.h }, z0.h[1]
	WORD	$0xc152b509	// fdot za.s[w9, 1, vgx4], { z8.h - z11.h }, z2.h[1]
	WORD	$0xa042a14c	// ld1h { z12.h - z15.h }, pn8/z, [x10, #0x8, mul vl]
	WORD	$0xc150998a	// fdot za.s[w8, 2, vgx4], { z12.h - z15.h }, z0.h[2]
	WORD	$0xc152b98a	// fdot za.s[w9, 2, vgx4], { z12.h - z15.h }, z2.h[2]
	WORD	$0xa043a150	// ld1h { z16.h - z19.h }, pn8/z, [x10, #0xc, mul vl]
	WORD	$0xc1509e0b	// fdot za.s[w8, 3, vgx4], { z16.h - z19.h }, z0.h[3]
	WORD	$0xc152be0b	// fdot za.s[w9, 3, vgx4], { z16.h - z19.h }, z2.h[3]
	WORD	$0x9110014a	// add x10, x10, #0x400
	WORD	$0xa040a144	// ld1h { z4.h - z7.h }, pn8/z, [x10]
	WORD	$0xc151908c	// fdot za.s[w8, 4, vgx4], { z4.h - z7.h }, z1.h[0]
	WORD	$0xc153b08c	// fdot za.s[w9, 4, vgx4], { z4.h - z7.h }, z3.h[0]
	WORD	$0xa041a148	// ld1h { z8.h - z11.h }, pn8/z, [x10, #0x4, mul vl]
	WORD	$0xc151950d	// fdot za.s[w8, 5, vgx4], { z8.h - z11.h }, z1.h[1]
	WORD	$0xc153b50d	// fdot za.s[w9, 5, vgx4], { z8.h - z11.h }, z3.h[1]
	WORD	$0xa042a14c	// ld1h { z12.h - z15.h }, pn8/z, [x10, #0x8, mul vl]
	WORD	$0xc151998e	// fdot za.s[w8, 6, vgx4], { z12.h - z15.h }, z1.h[2]
	WORD	$0xc153b98e	// fdot za.s[w9, 6, vgx4], { z12.h - z15.h }, z3.h[2]
	WORD	$0xa043a150	// ld1h { z16.h - z19.h }, pn8/z, [x10, #0xc, mul vl]
	WORD	$0xc1519e0f	// fdot za.s[w8, 7, vgx4], { z16.h - z19.h }, z1.h[3]
	WORD	$0xc153be0f	// fdot za.s[w9, 7, vgx4], { z16.h - z19.h }, z3.h[3]
	WORD	$0x9110014a	// add x10, x10, #0x400
	WORD	$0x9100816b	// add x11, x11, #0x20
	WORD	$0x910082b5	// add x21, x21, #0x20
	WORD	$0xd100058c	// sub x12, x12, #0x1
	WORD	$0x17ffffde	// b 0x48
	WORD	$0x052603ff	// ext z31.b, z31.b, z31.b, #0x30
	WORD	$0x1e2603ee	// fmov w14, s31
	WORD	$0x3400110e	// cbz w14, 0x2fc
	WORD	$0xc0060c00	// mov { z0.d - z3.d }, za.d[w8, 0, vgx4]
	WORD	$0xc0060c24	// mov { z4.d - z7.d }, za.d[w8, 1, vgx4]
	WORD	$0x65840000	// fadd z0.s, z0.s, z4.s
	WORD	$0x65850021	// fadd z1.s, z1.s, z5.s
	WORD	$0x65860042	// fadd z2.s, z2.s, z6.s
	WORD	$0x65870063	// fadd z3.s, z3.s, z7.s
	WORD	$0xc0060c44	// mov { z4.d - z7.d }, za.d[w8, 2, vgx4]
	WORD	$0x65840000	// fadd z0.s, z0.s, z4.s
	WORD	$0x65850021	// fadd z1.s, z1.s, z5.s
	WORD	$0x65860042	// fadd z2.s, z2.s, z6.s
	WORD	$0x65870063	// fadd z3.s, z3.s, z7.s
	WORD	$0xc0060c64	// mov { z4.d - z7.d }, za.d[w8, 3, vgx4]
	WORD	$0x65840000	// fadd z0.s, z0.s, z4.s
	WORD	$0x65850021	// fadd z1.s, z1.s, z5.s
	WORD	$0x65860042	// fadd z2.s, z2.s, z6.s
	WORD	$0x65870063	// fadd z3.s, z3.s, z7.s
	WORD	$0xc0060c84	// mov { z4.d - z7.d }, za.d[w8, 4, vgx4]
	WORD	$0x65840000	// fadd z0.s, z0.s, z4.s
	WORD	$0x65850021	// fadd z1.s, z1.s, z5.s
	WORD	$0x65860042	// fadd z2.s, z2.s, z6.s
	WORD	$0x65870063	// fadd z3.s, z3.s, z7.s
	WORD	$0xc0060ca4	// mov { z4.d - z7.d }, za.d[w8, 5, vgx4]
	WORD	$0x65840000	// fadd z0.s, z0.s, z4.s
	WORD	$0x65850021	// fadd z1.s, z1.s, z5.s
	WORD	$0x65860042	// fadd z2.s, z2.s, z6.s
	WORD	$0x65870063	// fadd z3.s, z3.s, z7.s
	WORD	$0xc0060cc4	// mov { z4.d - z7.d }, za.d[w8, 6, vgx4]
	WORD	$0x65840000	// fadd z0.s, z0.s, z4.s
	WORD	$0x65850021	// fadd z1.s, z1.s, z5.s
	WORD	$0x65860042	// fadd z2.s, z2.s, z6.s
	WORD	$0x65870063	// fadd z3.s, z3.s, z7.s
	WORD	$0xc0060ce4	// mov { z4.d - z7.d }, za.d[w8, 7, vgx4]
	WORD	$0x65840000	// fadd z0.s, z0.s, z4.s
	WORD	$0x65850021	// fadd z1.s, z1.s, z5.s
	WORD	$0x65860042	// fadd z2.s, z2.s, z6.s
	WORD	$0x65870063	// fadd z3.s, z3.s, z7.s
	WORD	$0x8b14220f	// add x15, x16, x20, lsl #8
	WORD	$0x8b14208e	// add x14, x4, x20, lsl #8
	WORD	$0xcb1418ad	// sub x13, x5, x20, lsl #6
	WORD	$0x25ad17e2	// whilelt p2.s, xzr, x13
	WORD	$0xa540a9e8	// ld1w { z8.s }, p2/z, [x15]
	WORD	$0x65880800	// fmul z0.s, z0.s, z8.s
	WORD	$0x65940800	// fmul z0.s, z0.s, z20.s
	WORD	$0xe540e9c0	// st1w { z0.s }, p2, [x14]
	WORD	$0xd10041ad	// sub x13, x13, #0x10
	WORD	$0x25ad17e2	// whilelt p2.s, xzr, x13
	WORD	$0xa541a9e8	// ld1w { z8.s }, p2/z, [x15, #0x1, mul vl]
	WORD	$0x65880821	// fmul z1.s, z1.s, z8.s
	WORD	$0x65940821	// fmul z1.s, z1.s, z20.s
	WORD	$0xe541e9c1	// st1w { z1.s }, p2, [x14, #0x1, mul vl]
	WORD	$0xd10041ad	// sub x13, x13, #0x10
	WORD	$0x25ad17e2	// whilelt p2.s, xzr, x13
	WORD	$0xa542a9e8	// ld1w { z8.s }, p2/z, [x15, #0x2, mul vl]
	WORD	$0x65880842	// fmul z2.s, z2.s, z8.s
	WORD	$0x65940842	// fmul z2.s, z2.s, z20.s
	WORD	$0xe542e9c2	// st1w { z2.s }, p2, [x14, #0x2, mul vl]
	WORD	$0xd10041ad	// sub x13, x13, #0x10
	WORD	$0x25ad17e2	// whilelt p2.s, xzr, x13
	WORD	$0xa543a9e8	// ld1w { z8.s }, p2/z, [x15, #0x3, mul vl]
	WORD	$0x65880863	// fmul z3.s, z3.s, z8.s
	WORD	$0x65940863	// fmul z3.s, z3.s, z20.s
	WORD	$0xe543e9c3	// st1w { z3.s }, p2, [x14, #0x3, mul vl]
	WORD	$0xc0062c00	// mov { z0.d - z3.d }, za.d[w9, 0, vgx4]
	WORD	$0xc0062c24	// mov { z4.d - z7.d }, za.d[w9, 1, vgx4]
	WORD	$0x65840000	// fadd z0.s, z0.s, z4.s
	WORD	$0x65850021	// fadd z1.s, z1.s, z5.s
	WORD	$0x65860042	// fadd z2.s, z2.s, z6.s
	WORD	$0x65870063	// fadd z3.s, z3.s, z7.s
	WORD	$0xc0062c44	// mov { z4.d - z7.d }, za.d[w9, 2, vgx4]
	WORD	$0x65840000	// fadd z0.s, z0.s, z4.s
	WORD	$0x65850021	// fadd z1.s, z1.s, z5.s
	WORD	$0x65860042	// fadd z2.s, z2.s, z6.s
	WORD	$0x65870063	// fadd z3.s, z3.s, z7.s
	WORD	$0xc0062c64	// mov { z4.d - z7.d }, za.d[w9, 3, vgx4]
	WORD	$0x65840000	// fadd z0.s, z0.s, z4.s
	WORD	$0x65850021	// fadd z1.s, z1.s, z5.s
	WORD	$0x65860042	// fadd z2.s, z2.s, z6.s
	WORD	$0x65870063	// fadd z3.s, z3.s, z7.s
	WORD	$0xc0062c84	// mov { z4.d - z7.d }, za.d[w9, 4, vgx4]
	WORD	$0x65840000	// fadd z0.s, z0.s, z4.s
	WORD	$0x65850021	// fadd z1.s, z1.s, z5.s
	WORD	$0x65860042	// fadd z2.s, z2.s, z6.s
	WORD	$0x65870063	// fadd z3.s, z3.s, z7.s
	WORD	$0xc0062ca4	// mov { z4.d - z7.d }, za.d[w9, 5, vgx4]
	WORD	$0x65840000	// fadd z0.s, z0.s, z4.s
	WORD	$0x65850021	// fadd z1.s, z1.s, z5.s
	WORD	$0x65860042	// fadd z2.s, z2.s, z6.s
	WORD	$0x65870063	// fadd z3.s, z3.s, z7.s
	WORD	$0xc0062cc4	// mov { z4.d - z7.d }, za.d[w9, 6, vgx4]
	WORD	$0x65840000	// fadd z0.s, z0.s, z4.s
	WORD	$0x65850021	// fadd z1.s, z1.s, z5.s
	WORD	$0x65860042	// fadd z2.s, z2.s, z6.s
	WORD	$0x65870063	// fadd z3.s, z3.s, z7.s
	WORD	$0xc0062ce4	// mov { z4.d - z7.d }, za.d[w9, 7, vgx4]
	WORD	$0x65840000	// fadd z0.s, z0.s, z4.s
	WORD	$0x65850021	// fadd z1.s, z1.s, z5.s
	WORD	$0x65860042	// fadd z2.s, z2.s, z6.s
	WORD	$0x65870063	// fadd z3.s, z3.s, z7.s
	WORD	$0x8b14220f	// add x15, x16, x20, lsl #8
	WORD	$0x8b06008e	// add x14, x4, x6
	WORD	$0x8b1421ce	// add x14, x14, x20, lsl #8
	WORD	$0xcb1418ad	// sub x13, x5, x20, lsl #6
	WORD	$0x25ad17e2	// whilelt p2.s, xzr, x13
	WORD	$0xa540a9e8	// ld1w { z8.s }, p2/z, [x15]
	WORD	$0x65880800	// fmul z0.s, z0.s, z8.s
	WORD	$0x65950800	// fmul z0.s, z0.s, z21.s
	WORD	$0xe540e9c0	// st1w { z0.s }, p2, [x14]
	WORD	$0xd10041ad	// sub x13, x13, #0x10
	WORD	$0x25ad17e2	// whilelt p2.s, xzr, x13
	WORD	$0xa541a9e8	// ld1w { z8.s }, p2/z, [x15, #0x1, mul vl]
	WORD	$0x65880821	// fmul z1.s, z1.s, z8.s
	WORD	$0x65950821	// fmul z1.s, z1.s, z21.s
	WORD	$0xe541e9c1	// st1w { z1.s }, p2, [x14, #0x1, mul vl]
	WORD	$0xd10041ad	// sub x13, x13, #0x10
	WORD	$0x25ad17e2	// whilelt p2.s, xzr, x13
	WORD	$0xa542a9e8	// ld1w { z8.s }, p2/z, [x15, #0x2, mul vl]
	WORD	$0x65880842	// fmul z2.s, z2.s, z8.s
	WORD	$0x65950842	// fmul z2.s, z2.s, z21.s
	WORD	$0xe542e9c2	// st1w { z2.s }, p2, [x14, #0x2, mul vl]
	WORD	$0xd10041ad	// sub x13, x13, #0x10
	WORD	$0x25ad17e2	// whilelt p2.s, xzr, x13
	WORD	$0xa543a9e8	// ld1w { z8.s }, p2/z, [x15, #0x3, mul vl]
	WORD	$0x65880863	// fmul z3.s, z3.s, z8.s
	WORD	$0x65950863	// fmul z3.s, z3.s, z21.s
	WORD	$0xe543e9c3	// st1w { z3.s }, p2, [x14, #0x3, mul vl]
	WORD	$0x052603ff	// ext z31.b, z31.b, z31.b, #0x30
	WORD	$0x1e2603ee	// fmov w14, s31
	WORD	$0x3400010e	// cbz w14, 0x2fc
	WORD	$0x8b070000	// add x0, x0, x7
	WORD	$0x91000694	// add x20, x20, #0x1
	WORD	$0xeb02029f	// cmp x20, x2
	WORD	$0x54ffe98b	// b.lt 0x1c
	WORD	$0xd503467f	// smstop
	WORD	$0xaa1103e0	// mov x0, x17
	WORD	$0x14000003	// b 0x304
	WORD	$0x91000631	// add x17, x17, #0x1
	WORD	$0x17ffff47	// b 0x1c
	MOVD	R0, retries+72(FP)
	RET

// func smeVectorBytes() int
TEXT ·smeVectorBytes(SB), NOSPLIT, $0-8
	WORD	$0x04bf5820	// rdsvl x0, #1
	MOVD	R0, ret+0(FP)
	RET
